### ISSUE TITLE
RAS date in DMR system

### ISSUE THREAD

**Issue by Yorch23** [lwvmobile/dsd-fme#101]
Hello,
I follow with great interest the advances made on DSD-FME in data collection, is there a possibility of knowing (key aliases) and (key value) of RAS?

Thanks

**Comment by lwvmobile** [comment]
I'm afraid not, I don't have any information on RAS other than a little speculation on the RAS enabled bits in the BPTC interleave and the ability to bypass the bad CRC checksum. I don't have any information on how RAS is applied or how a key is applied to it. For the context of DSD-FME, I don't know that even knowing how to do so, or being able to do so, would be very beneficial, other than confirming good data with a valid CRC.

**Comment by s58sms** [comment]
I think you can get i key with airtracer, proper motorola radio connected to pc/sowtfare and signal with ras enabled.
