### ISSUE TITLE
New mode 

### ISSUE THREAD

**Issue by ahlawy81** [lwvmobile/dsd-fme#102]
I've recorded those signals on 72 and 68 mhz
I don't thinks it's one of known modes
After searching I think it's 90 % stanag 4204 which is not implemented in any decoding software yet. 
Worth a shot
https://wetransfer.com/downloads/eae715c0037ef62e1b2ba869a94583c620230131215915/c20367

**Comment by lwvmobile** [comment]
Well, with no confirmation, and no real information to go on for that standard, I won't be able to do much with it. Considering that its USDoD level stuff, its probably best to leave it alone.

**Comment by ahlawy81** [comment]
Hey, thanks for your reply
I'm 90% sure it's sincgars I'll do my best to analysis it till then I think it's fsk or psk modulation

**Comment by ahlawy81** [comment]
I wonder what's needed to implement a decoder for it
Like knowing it's digital mode
Baud rate
What else?
