### ISSUE TITLE
Segmentation fault with file without extension

### ISSUE THREAD

**Issue by AlexeyGS** [lwvmobile/dsd-fme#105]
If I enter a file name without an extension, like this "dsd-fme -i file", a "segmentation fault" error will appear. 
This happens in the "openAudioInDevice" function, in the "dsd_audio.c" file, line 601, because the extension is NULL.

**Comment by lwvmobile** [comment]
What kind of file are you trying to open? The arguments for -i are filename.bin file for capture bins, filename.wav for wav files, and other devices like -i pulse, -i tcp:parms, or -i rtl:parms.

**Comment by AlexeyGS** [comment]
Raw PCM_16 without wav header files, for example. Or named pipe.

**Comment by lwvmobile** [comment]
DSD-FME doesn't have any handling for named input pipes, too obscure of a use case, if you can convert it to a standard input pipe `-i -` then it would read in as PCM_16_LE audio. In the future, I'll try to include handling for it.

**Comment by lwvmobile** [comment]
Okay, I've pushed a fix for this issue

https://github.com/lwvmobile/dsd-fme/commit/304b5545ba6ddf720f82b62f4ef6ee942ea17e11

If you would, just pull the latest and rebuild, see if it will work for you now with your named pipes and which ever other schemes you wish, it'll treat it like a PCM_16_LE wav file, same as the usual wav input and tcp audio input.

**Comment by AlexeyGS** [comment]
No, it doesn't work for named pipe. Because named pipe works like stdin. 
Code below works, but it may need to add a separate type for named pipes.

```
else if (extension == NULL) {
        opts->audio_in_type = 1;
        opts->audio_in_file_info = calloc(1, sizeof(SF_INFO));
        opts->audio_in_file_info->samplerate = opts->wav_sample_rate;
        opts->audio_in_file_info->channels = 1;
        opts->audio_in_file_info->seekable = 0;
        opts->audio_in_file_info->format = SF_FORMAT_RAW | SF_FORMAT_PCM_16 | SF_ENDIAN_LITTLE;
        opts->audio_in_file = sf_open(opts->audio_in_dev, SFM_READ, opts->audio_in_file_info);

        if (opts->audio_in_file == NULL) {
            fprintf(stderr, "Error, couldn't open stdin with libsndfile: %s\n", sf_strerror(NULL));
            exit(1);
        }
    }
```

**Comment by lwvmobile** [comment]
Closed as completed
