### ISSUE TITLE
DMR Data PI Header PDU

### ISSUE THREAD

**Issue by Dmedia3412** [lwvmobile/dsd-fme#108]
Hello!

Please add PI Header processing for DMR Data .
After all, it already exists for DMR Voice.

**Comment by lwvmobile** [comment]
The PI header is already in there.

**Comment by Dmedia3412** [comment]
SD:D [DD_HEAD] - SAP 09 [Prop PDU] - BLOCKS 03 - DD 00 - PADb 56 - FMT 00 [Binary]
 DMR PDU Payload [0D][93][00][00][01][37][19][86][01][38][B1][DA]
09:18:39 Sync: +DMR   slot1  [slot2] | Color Code=01 | IDLE
09:18:39 Sync: +DMR  [slot1]  slot2  | Color Code=01 | DATA
 Slot 1 Data Header - Proprietary Packet Data - P_SAP 10 [Short DT] - MFID 10 [Motorola]
 DMR PDU Payload [AF][10][11][02][00][00][1D][08][5F][1B][C7][9A]
 SLCO NULL
09:18:39 Sync: +DMR   slot1  [slot2] | Color Code=01 | IDLE
09:18:39 Sync: +DMR  [slot1]  slot2  | Color Code=01 | R12U
 DMR PDU Payload [F0][D7][6F][08][F4][B8][E8][E9][26][8A][1A][52]
09:18:39 Sync: +DMR   slot1  [slot2] | Color Code=01 | IDLE
09:18:39 Sync: +DMR  [slot1]  slot2  | Color Code=01 | R12U
 Slot 1 - Multi Block PDU Message
  [F0][D7][6F][08][F4][B8][E8][E9][26][8A][1A][52]
  [11][00][00][00][00][00][00][00][25][EB][14][F2]

 Short Data: ASCII
  o     &  R        %
 DMR PDU Payload [11][00][00][00][00][00][00][00][25][EB][14][F2]
 SLCO Activity Update TS1: B Hash: E3 TS2: 0 Hash: 00
 SLCO Completed Block [1B][0E][30][08][00]

Here I don't see the PI header.

But I see this PDU [AF][10][11][02-KID][00][00] [1D085F1B-MI][C7][9A] I'm not sure where the ALG ID is in that.

**Comment by Dmedia3412** [comment]
Because the data is encrypted and I see KID&MI in the PDU, the decrypted data looks like this for this packet.

[02 Reg-check] 00 11 00 03 00 04 0c [371986 - RID] 49
[03 Reg-req]
Yes, this is xxtera proprietary data, these are RRS registration packages

**Comment by lwvmobile** [comment]
> Yes, this is **_xxtera_** proprietary data, these are RRS registration packages



> Slot 1 Data Header - Proprietary Packet Data - P_SAP 10 [Short DT] - MFID 10 [**_Motorola_**]

That's not what the P_HEAD MFID says.

**Comment by Dmedia3412** [comment]
SD:D [DD_HEAD] - SAP 10 [Short DT] - BLOCKS 02 - DD 00 - PADb 56 - FMT 00 [Binary]
 DMR PDU Payload [0D][A2][00][00][01][37][09][E7][01][38][19][07]
11:26:15 Sync: +DMR  [slot1]  slot2  | Color Code=01 | IDLE
11:26:15 Sync: +DMR   slot1  [slot2] | Color Code=01 | R12U
 DMR PDU Payload [02][00][11][00][03][00][04][0C][37][09][E7][F8]
11:26:15 Sync: +DMR  [slot1]  slot2  | Color Code=01 | IDLE
 SLCO Activity Update TS1: 0 Hash: 00 TS2: A Hash: 07
 SLCO Completed Block [10][A0][00][78][40]
11:26:15 Sync: +DMR   slot1  [slot2] | Color Code=01 | R12U
 Slot 2 - Multi Block PDU Message
  [02][00][11][00][03][00][04][0C][37][09][E7][F8]
  [03][00][00][00][00][00][00][00][11][FA][6F][96]

 Short Data: ASCII
        7             o
 DMR PDU Payload [03][00][00][00][00][00][00][00][11][FA][6F][96]
11:26:15 Sync: +DMR  [slot1]  slot2  | Color Code=01 | IDLE
11:26:15 Sync: +DMR   slot1  [slot2] | Color Code=01 | IDLE
11:26:15 Sync: +DMR  [slot1]  slot2  | Color Code=01 | IDLE
 SLCO Activity Update TS1: 0 Hash: 00 TS2: A Hash: 07
 SLCO Completed Block [10][A0][00][78][40]

This is how they look when encryption is disabled

**Comment by lwvmobile** [comment]
Well, that may be so, but again, I don't have enough information to go off of in this case without first hand knowledge, which I admit, I am lacking in a lot of elements here.

What I will say, however, is that if you have a reasonable expectation that certain data elements should be present, and you wish to add them for yourself, you can freely modify the code to your own liking to extract certain decoded elements of your choosing, or your interpretation of them as you see fit. I would suggest looking in src/dmr_block.c for the dmr_dheader function and studying how elements are extracted from the bits, and copying and making new variables to your liking and having them print to the console at your liking during the p_head, for example, might I suggest using this code:

```
uint8_t p_alg = (uint8_t)ConvertBitIntoBytes(&dheader_bits[16], 8);
uint8_t p_key = (uint8_t)ConvertBitIntoBytes(&dheader_bits[24], 8);
uint32_t p_mi = (uint32_t)ConvertBitIntoBytes(&dheader_bits[48], 32);
```

if you believe that's what these bits convey during certain p_head pdus.

https://github.com/lwvmobile/dsd-fme/blob/main/src/dmr_block.c

**Comment by lwvmobile** [comment]
Well, if you can provide samples (wav files, preferably in this instance) and tell me exactly what I should expect in the data packets including what the packet is conveying and any relevant numbers like opcodes, sap/format, Radio IDs, etc, then I can look into it. I can't promise anything, or that I'll add it right away. I had planned on taking a bit of a break from coding for a while. 

Keep in mind, I'll only add things that are not enc, so that most likely means that adding your MI/ALG/Key info on the P_HEAD may be out of the main code unless it can be determined by opcode or something that that p_head always carries that info every time its present and can't be confused for any other p_head pdu. Even if it is included, I will most likely not be including a means to decrypt it, even if its alg is a known alg.

If you wish to submit information and links to wav files, etc, probably the easiest thing would be to zip up any relevant wav files and txt documents with descriptions and upload them to a hosting service such as https://ufile.io/ where users don't need to log in or register (so, no mega or google drive, etc, unless its a clear link to a download not requiring log in, etc) then I will review anything you submit when I have time, and see if I can work anything out from that information.

**Comment by lwvmobile** [comment]
Well, the more I ponder about this when I revisit and see the header and issue here, is that if all you want to see if the MI value (or whatever is in the P_HEAD), then if you enable the payload printer with the -Z option, it will tell you what those byte values are. As mentioned, I don't intend to add anything further to attempt to decrypt them, and if you can see the bytes, then you don't really need me to gather them and present them as MI: 0xXXXXXXXX or similar if you know that's what it is.

I never like to turn down a request, but I think its probably better just to close this one as 'won't be worked on' as I just don't see any value in this particular request. Sorry :(

**Comment by Dmedia3412** [comment]
Yes, I see KID, MI, but I don't see ALG id. I wanted to ask you to implement PI Header Data display like PI Header Voice.
It doesn't decrypt anything, it doesn't provide any secret information just like PI Header Voice. Without the value of the encryption key, this information is of no value. But I understood you that you are not interested in this and you will not do it. Sincerely! Thanks for your work.
