### ISSUE TITLE
WIP: NXDN Type D - 'IDAS' Support: Ongoing Work

### ISSUE THREAD

**Issue by lwvmobile** [lwvmobile/dsd-fme#115]
I have run across some Type-D 'IDAS' systems and will add some very initial support for them, the first step will be to just identify them as Type D or IDAS by using the relevant LICH codes found in Part 1-E Common Air Interface Ver.1.3 and having the console output a distinct frame sync pattern for those as opposed to NXDN48, and identify which elements are present in the LICH codes, i.e. SCCH, FACCH3, UDCH2, and any other confusing and superfluous acronyms you can think of.

![Screenshot from 2023-04-13 13-59-26](https://user-images.githubusercontent.com/59371473/231888462-bf3fa249-6097-489a-943b-55170e0689ab.png)

```
17:48:15 Sync: IDAS D  L61 - Data   SCCH  VCALL
 Group Call - Half Duplex 4800bps/EHR - Src=20550 - Dst/TG=20550  VCALL
 Group Call - Half Duplex 4800bps/EHR - Src=20550 - Dst/TG=20550 
17:48:15 Sync: IDAS D  L77 - Voice  SCCH 
17:48:15 Sync: IDAS D  L77 - Voice  SCCH 
17:48:15 Sync: IDAS D  L77 - Voice  SCCH 
17:48:15 Sync: IDAS D  L77 - Voice  SCCH 
17:48:15 Sync: IDAS D  L77 - Voice  SCCH 
17:48:15 Sync: IDAS D  L77 - Voice  SCCH 
17:48:15 Sync: IDAS D  L77 - Voice  SCCH 
17:48:16 Sync: IDAS D  L77 - Voice  SCCH 
17:48:16 Sync: IDAS D  L77 - Voice  SCCH 
17:48:16 Sync: IDAS D  L77 - Voice  SCCH 
17:48:16 Sync: IDAS D  L77 - Voice  SCCH 
17:48:16 Sync: IDAS D  L77 - Voice  SCCH 
17:48:16 Sync: IDAS D  L77 - Voice  SCCH 
17:48:16 Sync: IDAS D  L77 - Voice  SCCH 
17:48:16 Sync: IDAS D  L77 - Voice  SCCH 
17:48:16 Sync: IDAS D  L77 - Voice  SCCH 
17:48:16 Sync: IDAS D  L77 - Voice  SCCH 
17:48:16 Sync: IDAS D  L77 - Voice  SCCH 
17:48:16 Sync: IDAS D  L77 - Voice  SCCH 
17:48:16 Sync: IDAS D  L77 - Voice  SCCH 
17:48:17 Sync: IDAS D  L77 - Voice  SCCH 
17:48:17 Sync: IDAS D  L77 - Voice  SCCH 
17:48:17 Sync: IDAS D  L77 - Voice  SCCH 
17:48:17 Sync: IDAS D  L77 - Voice  SCCH 
17:48:17 Sync: IDAS D  L77 - Voice  SCCH 
17:48:17 Sync: IDAS D  L77 - Voice  SCCH 
17:48:17 Sync: IDAS D  L77 - Voice  SCCH 
17:48:17 Sync: IDAS D  L77 - Voice  SCCH 
17:48:17 Sync: IDAS D  L61 - Data   SCCH  TX_REL TX_REL
17:48:17 Sync: IDAS D  L61 - Data   SCCH  DISC DISC


```

Later on, I'll chip away at adding handling for SCCH deperm/depunc, crc, and relevant message decoding. Same for FACCH3, and UDCH2. I have no time table for completing this, let alone being able to trunk it, but I would suspect it may work similarly to Capacity Plus or Hytera XPT based on the nature of Type D and its short bursts and 'free repeater' messages.

**Comment by didier02000** [comment]
bonjour je voudrais savoir si vous pouvez changer la couleur du scrambler quand on a placer notre clé  exemple  en vert 
![scrambeler](https://user-images.githubusercontent.com/54736600/232590920-9427bc04-9235-48da-b6b5-ce0cbd00b4d7.jpg)
merci super boulot

**Comment by lwvmobile** [comment]
> bonjour je voudrais savoir si vous pouvez changer la couleur du scrambler quand on a placer notre clé et elle les active exemple en vert

Unfortunately, there is no user options for changing colors in the ncurses terminal. You can either disable all color by building from the source code with the cmake option `cmake -DCOLOR=OFF ..` or in the precompiled newest release version, there is another exe file named dsd-fme-aero-nc.exe which is completely colorless.

Alternatively, for those who compile their own, you can look at the color_pairs here, and change these values as you see fit, or customize things to your liking. I think even this minor modification can be made by most people without an extensive understanding of the code in general. Just remember, if you make changes to the source code, you'll need to run `make` and `make install` again to build and install with the changes.

For example, you could change any of these pairs to your liking, but ncurses colors are fairly limited on availability.

https://github.com/lwvmobile/dsd-fme/blob/main/src/dsd_ncurses.c#L380

```
  init_pair(1, COLOR_YELLOW, COLOR_BLACK);      //Yellow/Amber for frame sync/control channel, NV style
  init_pair(2, COLOR_RED, COLOR_BLACK);        //Red for Terminated Calls
  init_pair(3, COLOR_GREEN, COLOR_BLACK);     //Green for Active Calls
  init_pair(4, COLOR_CYAN, COLOR_BLACK);     //Cyan for Site Extra and Patches
  init_pair(5, COLOR_MAGENTA, COLOR_BLACK); //Magenta for no frame sync/signal
  init_pair(6, COLOR_WHITE, COLOR_BLACK);  //White Card Color Scheme
```

Or, if you just wish for specific elements in ncurses to be a different color, you could remove the attron or change it to your liking

https://github.com/lwvmobile/dsd-fme/blob/main/src/dsd_ncurses.c#L2311

```
    if (state->nxdn_cipher_type == 0x1 && state->carrier == 1)
    {
      attron(COLOR_PAIR(2)); //turn on red color <--change this color_pair to any other number matching pairs in code example above
      printw ("Scrambler ");
      attroff(COLOR_PAIR(2)); //turn off red color
      attron(COLOR_PAIR(3)); 
      if (state->R != 0)
      {
        attron(COLOR_PAIR(1));
        printw ("KEY VALUE: [%05lld] ", state->R );
        printw ("SEED: [%04llX]", state->payload_miN);
        attron(COLOR_PAIR(3));
      }
    }
```

I hope this helps.

**Comment by didier02000** [comment]
merci bien je vais faire comme je peu si j arrive a le faire je vous tien au courant merci bien

**Comment by lwvmobile** [comment]
Well, I've had a week or so to chip away at 'IDAS' - Type D - and I've found that I was able to re-use a lot of code to handle SCCH, and FACCH3/UDCH2 deinterleaving/depunc/convolution, crc, etc. What I've found is that SCCH works almost exactly like SACCH, just the individual segments are 25 bit as opposed to a 26-bit SACCH, and its CRC is CRC7, as opposed to SACCH's CRC 6. With these minor changes made (just copy and paste SACCH and change a few things basically) I have SCCH handling for Type-D.

That being said, unlike SACCH, the messages that originate inside of SCCH are completely different than the conventional and Type-C message layout. They use a unique format that can be read after compiling each invidual 'unit' like SACCH, but what I've found (by mistake) is that each 'unit' or 'segment' of SCCH can be decoded separately as each 'unit' or 'segment' is a clean division of elements. The only exception is enc. IV, which can be stored and put back together. What I had originally coded by mistake may turn out to be more beneficial, as one bad CRC in a SCCH isn't going to discard the entire superframe, but just bypass the individual portion of the completed message that is bad. I should also note, that like SACCH, superframe structure is only used during voice and not during data.

Below, we can see the SCCH message format and how its cleanly divided (mostly) in each individual segment, also having repetitious information (most likely so each 'unit' can be read separately, much like RAN data in SACCH). Reading them separately will also allow 'quicker' trunking, I believe.

![Screenshot from 2023-04-15 15-55-50](https://user-images.githubusercontent.com/59371473/233728407-54501375-4ecd-4821-8901-5bbde53ed196.png)

![Screenshot from 2023-04-13 16-10-19](https://user-images.githubusercontent.com/59371473/233728738-e50f5a49-bdb6-4b59-a5b8-0c52b18e2d70.png)

I've also written some code to handle the ISM/OSM message format from SCCH and have some trunking on it. At this point, its just mostly in the testing phase, along with other additions and, hopefully, small improvements, to NXDN decoding and trunking in general.

This is a small decoded sample from a small (2 channel) Type-D system that isn't busy at all. Much like XPT, its just test it, observe the log, make sure its changing channels when its supposed to, and make tweaks here and there. 

```
16:13:46 Sync: IDAS D  RTCH2  Data   SCCH
 Busy Repeater Message - Area: 0; Go to Repeater: 2; Home Repeater: 10; 
 Channel Update - CH: 2 - TGT: 70 Group Call 
    Channel not found in import file IDLE IDLE
16:13:47 Sync: IDAS D  RTCH2  Data   SCCH
 Free Repeater Message - Area: 0; Free Repeater 1: 10; Free Repeater 2: 0;  IDLE IDLE
16:13:47 Sync: IDAS D  RTCH2  Data   SCCH (CRC ERR) FACCH (CRC ERR) FACCH (CRC ERR)
16:13:47 Sync: IDAS D  RTCH2  Voice  SCCH
 Target Message - Area: 0; Go to Repeater: 2; 
 Target Update - Prefix CH: 10 SRC: 70 - (10-70) 
16:13:47 Sync: IDAS D  RTCH2  Voice  SCCH
 Source Message - Area: 0; Free Repeater 1: 10; 
 Source Update - Prefix CH: 10 SRC: 75 - (10-75) 
16:13:47 Sync: IDAS D  RTCH2  Voice  SCCH
 Busy Repeater Message - Area: 0; Go to Repeater: 2; Home Repeater: 10; 
 Channel Update - CH: 2 - TGT: 70 Group Call 
    Channel not found in import file
16:13:47 Sync: IDAS D  RTCH2  Voice  SCCH
 Call Option - Area: 0; Free Repeater 1: 10; Free Repeater 2: 0; 
 Half Duplex 4800bps/EHR 
16:13:47 Sync: IDAS D  RTCH2  Voice  SCCH
 Target Message - Area: 0; Go to Repeater: 2; 
 Target Update - Prefix CH: 10 SRC: 70 - (10-70) 
16:13:47 Sync: IDAS D  RTCH2  Voice  SCCH
 Source Message - Area: 0; Free Repeater 1: 10; 
 Source Update - Prefix CH: 10 SRC: 75 - (10-75) 
16:13:47 Sync: IDAS D  RTCH2  Voice  SCCH
 Busy Repeater Message - Area: 0; Go to Repeater: 2; Home Repeater: 10; 
 Channel Update - CH: 2 - TGT: 70 Group Call 
    Channel not found in import file
16:13:47 Sync: IDAS D  RTCH2  Voice  SCCH
 Call Option - Area: 0; Free Repeater 1: 10; Free Repeater 2: 0; 
 Half Duplex 4800bps/EHR 
16:13:47 Sync: IDAS D  RTCH2  Voice  SCCH
 Target Message - Area: 0; Go to Repeater: 2; 
 Target Update - Prefix CH: 10 SRC: 70 - (10-70) 
16:13:48 Sync: IDAS D  RTCH2  Voice  SCCH
 Source Message - Area: 0; Free Repeater 1: 10; 
 Source Update - Prefix CH: 10 SRC: 75 - (10-75) 
16:13:48 Sync: IDAS D  RTCH2  Voice  SCCH
 Busy Repeater Message - Area: 0; Go to Repeater: 2; Home Repeater: 10; 
 Channel Update - CH: 2 - TGT: 70 Group Call 
    Channel not found in import file
16:13:48 Sync: IDAS D  RTCH2  Voice  SCCH
 Call Option - Area: 0; Free Repeater 1: 10; Free Repeater 2: 0; 
 Half Duplex 4800bps/EHR 
16:13:48 Sync: IDAS D  RTCH2  Voice  SCCH
 Target Message - Area: 0; Go to Repeater: 2; 
 Target Update - Prefix CH: 10 SRC: 70 - (10-70) 
16:13:48 Sync: IDAS D  RTCH2  Voice  SCCH
 Source Message - Area: 0; Free Repeater 1: 10; 
 Source Update - Prefix CH: 10 SRC: 75 - (10-75) 
16:13:48 Sync: IDAS D  RTCH2  Voice  SCCH
 Busy Repeater Message - Area: 0; Go to Repeater: 2; Home Repeater: 10; 
 Channel Update - CH: 2 - TGT: 70 Group Call 
    Channel not found in import file
16:13:48 Sync: IDAS D  RTCH2  Voice  SCCH
 Call Option - Area: 0; Free Repeater 1: 10; Free Repeater 2: 0; 
 Half Duplex 4800bps/EHR 
16:13:48 Sync: IDAS D  RTCH2  Voice  SCCH
 Target Message - Area: 0; Go to Repeater: 2; 
 Target Update - Prefix CH: 10 SRC: 70 - (10-70) 
16:13:48 Sync: IDAS D  RTCH2  Voice  SCCH
 Source Message - Area: 0; Free Repeater 1: 10; 
 Source Update - Prefix CH: 10 SRC: 75 - (10-75) 
16:13:48 Sync: IDAS D  RTCH2  Voice  SCCH
 Busy Repeater Message - Area: 0; Go to Repeater: 2; Home Repeater: 10; 
 Channel Update - CH: 2 - TGT: 70 Group Call 
    Channel not found in import file
16:13:48 Sync: IDAS D  RTCH2  Data   SCCH
 Busy Repeater Message - Area: 0; Go to Repeater: 31; Home Repeater: 10; 
 Channel Update - CH: 31 - TGT: 70 Group Call Termination 
    Channel not found in import file
 Group Call -   Transmission Release  - Src=75 - Dst/TG=70 - Ch: 10  TX_REL
 Group Call -   Transmission Release  - Src=75 - Dst/TG=70 - Ch: 10  TX_REL
16:13:48 Sync: IDAS D  RTCH2  Data   SCCH
 Free Repeater Message - Area: 0; Free Repeater 1: 10; Free Repeater 2: 0; 
 Group Call -        Disconnect       - Src=75 - Dst/TG=70 - Ch: 10  DISC
 Group Call -        Disconnect       - Src=75 - Dst/TG=70 - Ch: 10  DISC
16:13:48 Sync: IDAS D  RTCH2  Data   SCCH
 Free Repeater Message - Area: 0; Free Repeater 1: 10; Free Repeater 2: 0; 
 Group Call -        Disconnect       - Src=75 - Dst/TG=70 - Ch: 10  DISC
 Group Call -        Disconnect       - Src=75 - Dst/TG=70 - Ch: 10  DISC

```

Again, with most things, the code isn't quite ready yet, and needs rounds of testing and tweaks, making sure nothing is accidentally broken now, those sorts of things. I don't suspect Type-D is very popular or used much compared to Type-C, my sources tell me that a lot of Type-D systems upgraded to Type-C, the only remaining Type-D are the smaller systems where having a distributed system allows the use of all frequencies as opposed to sacrificing one (of two or three) RF channels to be full time control channel.

**Comment by lwvmobile** [comment]
> merci bien je vais faire comme je peu si j arrive a le faire je vous tien au courant merci bien

New release version will change from red to green now when a key is loaded, per your request.

https://github.com/lwvmobile/dsd-fme/releases/tag/win32-aero

**Comment by lwvmobile** [comment]
Completed as good as I can get it with what I have to work with;
