### ISSUE TITLE
WIP: Capacity Plus Expansion and Tweaks;

### ISSUE THREAD

**Issue by lwvmobile** [lwvmobile/dsd-fme#116]
I've recently come across an old Capacity Plus sample I had where the rest channel was 9 and 10, and talkgroup activity occurred on LSNs 1, and LSN 9 and 10; In the current code, I am only handling Capacity Plus up to 8 slots (4 RF channels), and any subsequent LSN activity would go undecoded. While it seems that much larger Capacity Plus sites  (anything above 8 slots) are rare compared to the smaller sites (as small as one repeater), I am going to be working on the code to allow for up to 16 LSNs. Doing a little test and observation, along with some notes and help from others (wriathe) and the sample I have, I have been able to identify when to look for additional activity in the completed Cap+ Channel Status CSBK. 

Usually, in the bit stream, we start at bit 24 and read 8 bits, one bit for each active LSN enumerated 1 through 8. If any of those bits are active (1) and not (0), then that corresponding slot has activity. We accumulate the active channels, and then subsequently, if any are active, we read the next 8 bits for that TG value. if 2 groups are active, we read the next 8 bits for the first group, then the next 8 bits for the next group. 

On larger systems, after we have parsed all active groups on LSN 1-8, we then have to look at the NEXT 8 bits. Those bits correspond to LSNs 9-16. On smaller systems, this is always 0, but on larger systems, we again take those 8 bits, one for each LSN 9-16, and if any are (1), then we read the next 8 bits for that TG value same as before.

For private data and voice calls, then, after we look at all the above (which can be a bit confusing, especially to write code for, because the size of the PDU is always variable and data is appended only as needed), we look at the next available 8 bits for a flag. I've found that if there is a flag (0x80) then that signifies private voice or data calls, then we read the NEXT 8-bits for active LSNs again for LSNs 1-8, if any of those bits are active (1), then we read the next 16-bits in the series to get that private target values. In Capacity Plus, Source and Private Target values are 16-bit, while Group/TG values are 8-bit.

As you can guess, (this is only my assumption at this point, since I don't have any samples to show this) if you have private voice or data calls on LSNs 9-16, then you repeat the same as above going to the next available 8-bits and so on and so on.

I've been working on the code to expand Capacity Plus decoding in this regard, but it may be a little while before I'm ready to release it, I want to make sure it doesn't break anything on smaller systems, while still allowing decoding and trunking on larger systems, and also that the code can handle random mixing of group and private calls in all sorts of LSN positions, making sure we can always read in the correct tg/tgt values for those (it gets tricky when you have a group call on 1, private call on 3, and another group call on 4 or 5, making sure we are accumulating positions and always knowing where to look for the next bit value.)

Here is the aforementioned sample of a larger Cap+ system with some of the updated code to handle it properly. We can see Rest Channel is 10, VLC TGT is 102, and activity occurring in LSN 1, LSN 9; 

```
18:14:29 Sync: +DMR  [slot1]  slot2  | Color Code=10 | VLC  
 SLOT 1 TGT=102 SRC=0 FLCO=0x04 FID=0x10 SVC=0x00 Cap+ Group Call  Cap+ R-Ch 10
 DMR PDU Payload [04][10][00][00][00][66][0A][00][00][70][35][97]

18:14:29 Sync: +DMR   slot1  [slot2] | Color Code=10 | CSBK
 Capacity Plus Channel Status - FL: 3 TS: 1 RS: 0 - Rest Channel 10 - Single Block
  LSN 01:   102;  LSN 02:  Idle;  LSN 03:  Idle;  LSN 04:  Idle;  
  LSN 05:  Idle;  LSN 06:  Idle;  LSN 07:  Idle;  LSN 08:  Idle;  
  LSN 09:   106;  LSN 10:  Rest;  LSN 11:  Idle;  LSN 12:  Idle;  
  LSN 13:  Idle;  LSN 14:  Idle;  LSN 15:  Idle;  LSN 16:  Idle;  
 DMR PDU Payload [BE][10][EA][80][66][80][6A][00][00][00][F2][13]

```

To verify I was doing this corretly, I've validated this activity against DSDPlus FL.

`+DMR                slot2    BS DATA       DCC=10  CSBK Cap+ RestCh=10 ActiveCh:TG=1:102,9:106`

Regardling Private Data or Voice Calls, I have samples of each. I should also point out, on data calls, much like I found in XPT, we need to handle Preamble CSBKs a bit differently. Preamble CSBKs also show the current rest channel, and Source value needs to be truncated to 16-bit as well. No special handling seems to needed on Data Headers (as far as I can tell) nor do they contain rest channels.

```
18:18:13 Sync: +DMR   slot1  [slot2] | Color Code=01 | CSBK
 Preamble CSBK - Individual Data - Source: 1 - Target: 653 - Rest Channel: 1 -RAS 4 
 DMR PDU Payload [BD][10][80][02][00][02][8D][01][00][01][E6][41]

18:18:13 Sync: +DMR  [slot1]  slot2  | Color Code=01 | CSBK
 Capacity Plus Channel Status - FL: 3 TS: 0 RS: 0 - Rest Channel 1 - Single Block
 F80 Private or Data Call -  LSN 02: TGT 653;
  LSN 01:  Rest;  LSN 02:   653;  LSN 03:  Idle;  LSN 04:  Idle;  
  LSN 05:  Idle;  LSN 06:  Idle;  LSN 07:  Idle;  LSN 08:  Idle;  
  
 DMR PDU Payload [BE][10][C1][00][00][80][40][02][8D][00][7A][95]
18:18:13 Sync: +DMR   slot1  [slot2] | Color Code=01 | DATA 
 Slot 2 Data Header - Indiv - Unconfirmed Delivery - Source: 1 Target: 653 
  SAP 09 [Prop PDU] - FMF 1 - BLOCKS 07 - PAD 09 - FSN 0 -RAS 4 
```

Private Voice:

```
18:20:33 Sync: +DMR  [slot1]  slot2  | Color Code=03 | VLC  
 SLOT 1 TGT=21001 SRC=21002 FLCO=0x07 FID=0x10 SVC=0x00 Cap+ Private Call  Cap+ R-Ch 4 
 DMR PDU Payload [07][10][00][00][52][09][04][52][0A][50][ED][7F]

18:20:33 Sync: +DMR   slot1  [slot2] | Color Code=03 | CSBK
 Capacity Plus Channel Status - FL: 3 TS: 1 RS: 0 - Rest Channel 4 - Single Block
 F80 Private or Data Call -  LSN 03: TGT 21001;
  LSN 01:  Idle;  LSN 02:  Idle;  LSN 03: 21001;  LSN 04:  Rest;  
  LSN 05:  Idle;  LSN 06:  Idle;  LSN 07:  Idle;  LSN 08:  Idle;  
 DMR PDU Payload [BE][10][E4][00][00][80][20][52][09][00][99][03]
```

The most difficult part is having both private calls (voice and data)  and group calls all mixed together and having more than one block of CSBK to append together, and then also parsing out the values into a presentable format. Once I think i have it down just right, I end up finding a combination of group and private in different LSN arrangements  and the private tgt values be incorrect suddenly.

```
18:38:08 Sync: +DMR   slot1  [slot2] | Color Code=01 | CSBK
 Capacity Plus Channel Status - FL: 2 TS: 1 RS: 0 - Rest Channel 4 - Initial Block
 DMR PDU Payload [BE][10][A4][80][3C][00][80][60][00][01][29][9F]

18:38:08 Sync: +DMR  [slot1]  slot2  | Color Code=01 | CSBK
 Capacity Plus Channel Status - FL: 1 TS: 0 RS: 0 - Rest Channel 4 - Final Block
 F80 Private or Data Call -  LSN 02: TGT 1; LSN 03: TGT 477;
  LSN 01:    60;  LSN 02:     1;  LSN 03:   477;  LSN 04:  Rest;  
  LSN 05:  Idle;  LSN 06:  Idle;  LSN 07:  Idle;  LSN 08:  Idle;  
 
 CAP+ Multi Block PDU 
  [BE][10][A4][80][3C][00][80][60][00][01][01][DD][00][00][00][00][00]
 DMR PDU Payload [BE][10][44][01][DD][00][00][00][00][00][D2][D4]
```

```
18:44:32 Sync: +DMR   slot1  [slot2] | Color Code=01 | CSBK
 Capacity Plus Channel Status - FL: 2 TS: 1 RS: 0 - Rest Channel 6 - Initial Block
 DMR PDU Payload [BE][10][A6][88][09][17][00][80][40][01][4A][52]

18:44:32 Sync: +DMR  [SLOT1]  slot2  | Color Code=01 | VC3 

18:44:32 Sync: +DMR   slot1  [slot2] | Color Code=01 | CSBK
 Capacity Plus Channel Status - FL: 1 TS: 1 RS: 0 - Rest Channel 6 - Final Block
 F80 Private or Data Call -  LSN 02: TGT 477;
  LSN 01:     9;  LSN 02:   477;  LSN 03:  Idle;  LSN 04:  Idle;  
  LSN 05:    23;  LSN 06:  Rest;  LSN 07:  Idle;  LSN 08:  Idle; 
```

**Comment by lwvmobile** [comment]
Another small thing I've just noticed, is regarding multiple blocks on this CSBK, they appear to be on a per slot basis, and not appended back to back. If they same CSBK type comes on on both slots simultaneously, then each slot is treated seperatately. If the system is not busy, this isn't a problem, but when stitching together initial blocks and final blocks, then they have to be seperated by timeslot, so I'll be adding that change in as well.

```
19:47:12 Sync: +DMR  [slot1]  slot2  | Color Code=01 | CSBK
 Capacity Plus Channel Status - FL: 2 TS: 0 RS: 0 - Rest Channel 5 - Initial Block
 DMR PDU Payload [BE][10][85][80][3C][00][80][10][00][01][CD][2C]

19:47:12 Sync: +DMR   slot1  [slot2] | Color Code=01 | CSBK
 Capacity Plus Channel Status - FL: 2 TS: 1 RS: 0 - Rest Channel 5 - Initial Block
 DMR PDU Payload [BE][10][A5][80][3C][00][80][10][00][01][B6][44]

 SLCO Capacity Plus Site: 1 - Rest Channel 5 - RS: 00
 SLCO Completed Block [F1][00][50][80][90]

19:47:12 Sync: +DMR  [slot1]  slot2  | Color Code=01 | CSBK
 Capacity Plus Channel Status - FL: 1 TS: 0 RS: 0 - Rest Channel 5 - Final Block
 F80 Private or Data Call -  LSN 04: TGT 1;
  LSN 01:    60;  LSN 02:  Idle;  LSN 03:  Idle;  LSN 04:     1;  
  LSN 05:  Rest;  LSN 06:  Idle;  LSN 07:  Idle;  LSN 08:  Idle;  
 CAP+ Multi Block PDU 
  [BE][10][85][80][3C][00][80][10][00][01][00][00][00][00][00][00][00]
 DMR PDU Payload [BE][10][45][00][00][00][00][00][00][00][C7][91]

19:47:12 Sync: +DMR   slot1  [slot2] | Color Code=01 | CSBK
 Capacity Plus Channel Status - FL: 1 TS: 1 RS: 0 - Rest Channel 5 - Final Block
 F80 Private or Data Call -  LSN 04: TGT 1;
  LSN 01:    60;  LSN 02:  Idle;  LSN 03:  Idle;  LSN 04:     1;  
  LSN 05:  Rest;  LSN 06:  Idle;  LSN 07:  Idle;  LSN 08:  Idle;  
 CAP+ Multi Block PDU 
  [BE][10][A5][80][3C][00][80][10][00][01][00][00][00][00][00][00][00]
 DMR PDU Payload [BE][10][65][00][00][00][00][00][00][00][BC][F9]

19:47:12 Sync: +DMR  [slot1]  slot2  | Color Code=01 | CSBK
 Capacity Plus Channel Status - FL: 2 TS: 0 RS: 0 - Rest Channel 5 - Initial Block
 DMR PDU Payload [BE][10][85][80][3C][00][80][10][00][01][CD][2C]

19:47:13 Sync: +DMR   slot1  [slot2] | Color Code=01 | CSBK
 Capacity Plus Channel Status - FL: 2 TS: 1 RS: 0 - Rest Channel 5 - Initial Block
 DMR PDU Payload [BE][10][A5][80][3C][00][80][10][00][01][B6][44]

 SLCO Capacity Plus Site: 1 - Rest Channel 5 - RS: 00
 SLCO Completed Block [F1][00][50][80][90]

19:47:13 Sync: +DMR  [slot1]  slot2  | Color Code=01 | CSBK
 Capacity Plus Channel Status - FL: 1 TS: 0 RS: 0 - Rest Channel 5 - Final Block
 F80 Private or Data Call -  LSN 04: TGT 1;
  LSN 01:    60;  LSN 02:  Idle;  LSN 03:  Idle;  LSN 04:     1;  
  LSN 05:  Rest;  LSN 06:  Idle;  LSN 07:  Idle;  LSN 08:  Idle;  
 CAP+ Multi Block PDU 
  [BE][10][85][80][3C][00][80][10][00][01][00][00][00][00][00][00][00]
 DMR PDU Payload [BE][10][45][00][00][00][00][00][00][00][C7][91]

19:47:13 Sync: +DMR   slot1  [slot2] | Color Code=01 | CSBK
 Capacity Plus Channel Status - FL: 1 TS: 1 RS: 0 - Rest Channel 5 - Final Block
 F80 Private or Data Call -  LSN 04: TGT 1;
  LSN 01:    60;  LSN 02:  Idle;  LSN 03:  Idle;  LSN 04:     1;  
  LSN 05:  Rest;  LSN 06:  Idle;  LSN 07:  Idle;  LSN 08:  Idle;  
 CAP+ Multi Block PDU 
  [BE][10][A5][80][3C][00][80][10][00][01][00][00][00][00][00][00][00]
 DMR PDU Payload [BE][10][65][00][00][00][00][00][00][00][BC][F9]

```

**Comment by lwvmobile** [comment]
Completed;

**Comment by lwvmobile** [comment]
Denny @DSheirer (SDRTrunk) has a system with some 0x90 pdflags, so going to include any value as a possible 'flag' or 'options' for the data or private call portion of Cap+.


> While updating sdrtrunk to parse the FID 0x10 CSBKO 62 site status messages, I found this example of a Cap+ Multi-Site system recording from Dallas, TX, where an additional bit is set in the data/private options bitmap. There's a cycling between using 0x80 and 0x90 for the data radio IDs bitmap. The 0x90 value seems to correlate with the timeslot where the activity will take place. This example is a data revert channel hosting LSN 1 & 2.

> I have several examples of this happening and have reasonably high confidence this is not a bit error.

> Initially I thought this might be a flag that indicates 'waiting for call parties to arrive on channel' since it seems to happen when there is a longer sequence of these status messages preceding the activity. However, I'm not sure that's accurate since you wouldn't be able to identify which LSN is waiting for additional radios to show up. But, if it's only sent on the channel/timeslot where the activity will occur, then maybe this is correct.

> I wanted to throw this example out there in case anyone is looking in code for a full 0x80 value versus simply looking for a high bit in the first nibble, for the options bitmap."

```
BE10E2000080803039000320 TS:2 CC:6 CSBK CAP+ SITE STATUS REST LSN:2 [FL] VOICE LSN 1-8:* 9-16:* DATA LSN 1:12345 2:* 3:* 4:* 5:* 6:* 7:* 8:*
BE10C2000090803039007C12 TS:1 CC:6 CSBK CAP+ SITE STATUS REST LSN:2 [FL] VOICE LSN 1-8:* 9-16:* DATA LSN 1:12345 2:* 3:* 4:* 5:* 6:* 7:* 8:*
BE10E2000080803039000320 TS:2 CC:6 CSBK CAP+ SITE STATUS REST LSN:2 [FL] VOICE LSN 1-8:* 9-16:* DATA LSN 1:12345 2:* 3:* 4:* 5:* 6:* 7:* 8:*
BE10C2000090803039007C12 TS:1 CC:6 CSBK CAP+ SITE STATUS REST LSN:2 [FL] VOICE LSN 1-8:* 9-16:* DATA LSN 1:12345 2:* 3:* 4:* 5:* 6:* 7:* 8:*
BE10E2000080803039000320 TS:2 CC:6 CSBK CAP+ SITE STATUS REST LSN:2 [FL] VOICE LSN 1-8:* 9-16:* DATA LSN 1:12345 2:* 3:* 4:* 5:* 6:* 7:* 8:*
BE10C2000090803039007C12 TS:1 CC:6 CSBK CAP+ SITE STATUS REST LSN:2 [FL] VOICE LSN 1-8:* 9-16:* DATA LSN 1:12345 2:* 3:* 4:* 5:* 6:* 7:* 8:*
BE10E2000080803039000320 TS:2 CC:6 CSBK CAP+ SITE STATUS REST LSN:2 [FL] VOICE LSN 1-8:* 9-16:* DATA LSN 1:12345 2:* 3:* 4:* 5:* 6:* 7:* 8:*
BE10C2000080803039007848 TS:1 CC:6 CSBK CAP+ SITE STATUS REST LSN:2 [FL] VOICE LSN 1-8:* 9-16:* DATA LSN 1:12345 2:* 3:* 4:* 5:* 6:* 7:* 8:*
BE10E2000080803039000320 TS:2 CC:6 CSBK CAP+ SITE STATUS REST LSN:2 [FL] VOICE LSN 1-8:* 9-16:* DATA LSN 1:12345 2:* 3:* 4:* 5:* 6:* 7:* 8:*
BE10C2000080803039007848 TS:1 CC:6 CSBK CAP+ SITE STATUS REST LSN:2 [FL] VOICE LSN 1-8:* 9-16:* DATA LSN 1:12345 2:* 3:* 4:* 5:* 6:* 7:* 8:*
BE10E2000080803039000320 TS:2 CC:6 CSBK CAP+ SITE STATUS REST LSN:2 [FL] VOICE LSN 1-8:* 9-16:* DATA LSN 1:12345 2:* 3:* 4:* 5:* 6:* 7:* 8:*
                         TS:1 CC:6 UNCONFIRMED DATA HEADER FM:1531 TO:12345 PROPRIETARY DATA BLOCKS TO FOLLOW:2 FRAGMENT SEQUENCE NUMBER:0(FINAL) PAD OCTETS:0
BE10E2000080803039000320 TS:2 CC:6 CSBK CAP+ SITE STATUS REST LSN:2 [FL] VOICE LSN 1-8:* 9-16:* DATA LSN 1:12345 2:* 3:* 4:* 5:* 6:* 7:* 8:*
                         TS:1 MOTOROLA MNIS HEADER APPLICATION:ARS PACKET:47089 PACKET PREFIX:0009F0 MSG:1F10020133B7F10009F081D5
BE10E2000080803039000320 TS:2 CC:6 CSBK CAP+ SITE STATUS REST LSN:2 [FL] VOICE LSN 1-8:* 9-16:* DATA LSN 1:12345 2:* 3:* 4:* 5:* 6:* 7:* 8:*
                         TS:1 CC:6 RATE 1/2 DATA CONFIRMED:313533310000A552A12F UNCONFIRMED:2004313533310000A552A12F
                         TS:1 CC:6 FM:1531 TO:12345 ARS DEVICE REGISTRATION-INITIAL DEVICE:1531
BE10E2000080803039000320 TS:2 CC:6 CSBK CAP+ SITE STATUS REST LSN:2 [FL] VOICE LSN 1-8:* 9-16:* DATA LSN 1:12345 2:* 3:* 4:* 5:* 6:* 7:* 8:*
```

Going to put it in the zDEV branch for now while I work on consolidating the Main and Aero branches into one singular codeset so I won't have to keep copying and pasting crap around between both of them.

**Comment by francisuk1989** [comment]
@lwvmobile Is this another Cap+ system your "might" be missing? - The system is just "bursting" every say 5mins, Fair as i know, there only two TG using the system, Is not encrypted.

Is it some sort of Radio check if not?
`https://www.transfer.sh/cpwNbaAqap/CapPlusMissing.wav`

**Comment by lwvmobile** [comment]
No, that's just a Tier 2 DMR repeater, no particular trunking or pseudo-trunking on it. All the messages from that beacon were just idle messages. Its not uncommon for some systems to just send out little idle bursts like that on a timer when there is no other activity.
