### ISSUE TITLE
Recording Output synthesized speech as .wav file

### ISSUE THREAD

**Issue by alphapats** [lwvmobile/dsd-fme#128]
The -w option helps to record Output synthesized speech to a .wav file,but it works for legacy auto modes only. 
Request if code can be modified to support recording output as wav file for all modes?

**Comment by lwvmobile** [comment]
I should perhaps rephrase that to mention that `-w filename.wav` 'works for anything but TDMA'.  The reason that it won't work with TDMA systems (DMR and P25 Phase 2) is that I cannot write dual voices to a single wav file from different slots with the current code. I can write them to separate files, but not the same file. 

Have you used or tried the `-P` per call wav file version instead? If you run per call wav file with the ncurses terminal running, it'll create seperate wav files for each call and assign it a name with the current Date/Time and  TG/SRC. If you run it without the ncurses terminal, then it will save voice to a static filename 'DSD-FME-X1.wav` or something like that.

**Comment by alphapats** [comment]
I tried -P option but it doesn't permit giving own file name and creates two files with same name everytime.

**Comment by lwvmobile** [comment]
Well, what kind of system are you trying to record calls from? What's your current startup command?

If its not DMR or Phase 2, you should still be able to use the -w switch anyways. If you do use the -P option, make sure to use it with the -N option for the ncurses terminal, as that terminal is what handles the naming of files (its tied into call history). For example, if I wanted to listen to a dmr system and wanted to make per call wav files, I would run the command.

`dsd-fme -fs -P -N 2> log.ans` 

and you would need to fill in any additional parameters if needed.
