### ISSUE TITLE
save each decoded sound to a separate file

### ISSUE THREAD

**Issue by GarryCZ** [lwvmobile/dsd-fme#131]
Hi, is it possible to save each decoded sound to a separate file? e.g. when it receives something at 13:00 , it saves it as 2023-06-06-13_00.wav and then when it receives it at 13:10 for example, it does 2023-06-06-13_10.wav

Thank you

**Comment by lwvmobile** [comment]
Yes, there is handling for Per Call Wav file saving, where as every call from a new source is recorded to a wav file and stored in the WAV file directory. To use it, you will want to run a command similar to `dsd-fme -N -P 2> log.ans` where as the ncurses terminal is running (which handles the per call wav files and call history) and can create new wav files for each new caller. Depending on which system type you want to decode and any additional features, you may need to supply additional switches at the command line or set them up in the ncurses terminal.

A lot of case uses can be viewed by looking at the help `dsd-fme -h`, by looking at the [Example Usage](https://github.com/lwvmobile/dsd-fme/blob/zDEV/examples/Example_Usage.md ) page and other information that can be found in the examples folder. If using the precompiled windows version in the release link, you can look at the bat files for examples as well.

If you have any questions about specific usage, or how to set up for a particular system type (i.e., DMR trunking, NXDN, etc) then feel free to ask away, and I can supply you with examples for those particular systems that you can try out if needed.
