### ISSUE TITLE
TODO: Trunking TG Hold

### ISSUE THREAD

**Issue by lwvmobile** [lwvmobile/dsd-fme#132]
Todo: Explore ways for a user to specify a single TG (while they are currently talking) as a hold, and only trunk track that individual group and allow other calls to be preempted to follow activity for that TG if necessary.

**Comment by francisuk1989** [comment]
+1 for follow activity for that TG

**Comment by lwvmobile** [comment]
I've got some tests set up in DMR decoding to handle TG Hold. User reports that T3 is working (still needs thorough testing) Cap+, XPT, and Con+ have not been tested yet. Its available in the audio_work branch for now. Use 'k' to hold on a TG that is currently talking in slot 1, hit 'k' again to release hold. Use 'l'  (lower case L) to hold on a TG that is currently talking in slot 2, hit 'l' or 'k' to release hold.

**Comment by francisuk1989** [comment]
@lwvmobile
Fantastic, I will give this ago over the weekend when back from holiday, with Cap+ and XPT, Sadly i dont have con+ here.

**Comment by lwvmobile** [comment]
I've been giving the TG Hold a test this morning on a busy Cap+ system with 10 LSNs, seems to do a pretty good job with following only the TG on hold by pre-empting other calls in progress on the rest channel, or if both slots are active with a group that isn't the TG hold group, then it'll tune itself to the current rest channel instead and wait for activity.

Also, I'll be pushing support for TG Hold for NXDN, EDACS, and P25 a little later on, I've already got NXDN and EDACS coded, just need to carefully go through all the call grants in P25 and make sure they are done just right, they have way too many types of call grants on P25, particularly the multiple call grant updates in one PDU.

**Comment by lwvmobile** [comment]
So, here is a question for TG Hold on TDMA systems (DMR and Phase 2) Would the preferred behavior be to still play the call audio for the call in the other slot during a TG hold, or to mute the audio of the call in the other slot if it isn't a TG hold? I was working on re-implementing the call audio mute on a Blocked TG, and put in the code for also doing it when a TG is in place and the slot isn't the TG on hold. I didn't know if it would be preferable to still be able to hear other traffic at times, or to just completely mute everybody but that single TG hold group.

**Comment by lwvmobile** [comment]
This is working pretty well now, so I'm going to go ahead and close it out.
