### ISSUE TITLE
RAS detection

### ISSUE THREAD

**Issue by JOULTICOA** [lwvmobile/dsd-fme#135]
Hello,

Thank you for this open source, modern DSD.  Please excuse my question here

I am hoping someone can highlight which checksum are altered in the below attached table from DMR Standards.

Question about RAS, and Motorola Capacity Max "Master Authentication Key" detection function.  Do these work the same way identically?  I see that the DSD detection seem to work on CapMax also so at a minimum, they must be similar.

Have you or other DSD contributors gained enough understanding on RAS and CapMax "Master Authentication Key" (note: not DRMA Tier 3 standard auth key, this is different) to highlight for me which of these checksums in attached picture are altered?

Is it just Voice LC Header and CSBK?  Or does RAS alter many checksums in addition to this?

I am hoping someone already has figure out an exhaustive / comprehensive list which checksum are altered, and which (if any) are left alone, this would be huge help!!

![DMR Checksums List](https://github.com/lwvmobile/dsd-fme/assets/74837290/03cb1ce2-42a7-4a63-94dc-936b50d20660)

**Comment by lwvmobile** [comment]
Thanks for taking interest in DSD-FME.

> Question about RAS, and Motorola Capacity Max "Master Authentication Key" detection function. Do these work the same way identically? I see that the DSD detection seem to work on CapMax also so at a minimum, they must be similar.

I honestly can't say that I know, regarding RAS and Motorola Capacity Max "Master Authentication Key". That's the first time I have ever heard that term before, so I can't say that they are the same thing or not, or work the same way or not. DSD-FME does indeed detect CapMax, but only does so by looking at certain Tier 3 CSBKs (ALOHA) and if it has an MFID of 0x10, then its deduced that its a capacity max system, and set's what it believes to be the correct site id appropriately (without the DMRLA sub area b.s.

> Is it just Voice LC Header and CSBK? Or does RAS alter many checksums in addition to this?

From my own personal observations, I have seen any Full Link Control (Voice LC Header, Termination LC Header, and Embeeded LC) all affected by RAS, as well as CSBK and Data Header (and presumably also the finale CRC on completed block messages following Data Headers. Its quite possible that any CRC is fair game for RAS manipulation, but those are just the ones I have personally observed on various systems to be affected. Which ones have RAS applied to them adn to which parts seems to vary from system to system. 

> I am hoping someone already has figure out an exhaustive / comprehensive list which checksum are altered, and which (if any) are left alone, this would be huge help!!

I honestly don't know if anybody has compiled a list of all things affected by RAS or not, or worked on ways of figuring out how a keystream is applied to RAS, but in my ever so brief study of it, I couldn't find anything concrete on RAS or its inner workings, the best I can do is to simply look for the reserved bit and when its flagged, allow a user to bypass the bad CRC.  From the point of view of DSD-FME, the only benefit to knowing how to apply RAS would be to be able to verify good data with a valid CRC vs having to bypass the CRC errors selectively.

**Comment by JOULTICOA** [comment]
Thank you very much

sounds like best to bypass all CRC
