### ISSUE TITLE
exitflag should not be static

### ISSUE THREAD

**Issue by volo-zyko** [lwvmobile/dsd-fme#136]
https://github.com/lwvmobile/dsd-fme/blob/8e230a08b562ae3dfb9c4d97baea5a55634183b3/include/dsd.h#L77

static variable is local to the current translation unit. Once it's declared in a header file every translation unit which includes the header will get its own copy of this variable. Indeed `nm` shows a number of instances of this variable in the compiled binary. I'd rather change it to `extern` (i.e. `extern volatile uint8_t exitflag;`) and define it `dsd_main.c` or similar as `volatile uint8_t exitflag;`. `uint8_t` is better than `int` because in a multi threaded environment there is no race when writing a single byte to memory. The same is not guaranteed to be true for `int`.

**Comment by lwvmobile** [comment]
Okay, thanks. I'll have it in the next batch of commits.
