### ISSUE TITLE
Useless line

### ISSUE THREAD

**Issue by volo-zyko** [lwvmobile/dsd-fme#137]
https://github.com/lwvmobile/dsd-fme/blob/8e230a08b562ae3dfb9c4d97baea5a55634183b3/src/dmr_data.c#L261-L262

It looks like the line with `-1` is useless.

**Comment by lwvmobile** [comment]
I'll look at this one with some tests, no idea why I had this like this, unless I was testing something and forgot to remove it, or just was blind to it after scrolling up and down the code so many times you see what you want to see, and not what is really there sometimes.

**Comment by volo-zyko** [comment]
Yes, it looks like some kind of testing.
