### ISSUE TITLE
symbol_out_file is never NULL

### ISSUE THREAD

**Issue by volo-zyko** [lwvmobile/dsd-fme#138]
https://github.com/lwvmobile/dsd-fme/blob/8e230a08b562ae3dfb9c4d97baea5a55634183b3/src/dsd_file.c#L578

It's probably meant `symbol_out_f`. Also, it would be a right thing to do `opts->symbol_out_f = NULL;` after `fclose` (but nothing critical).

**Comment by lwvmobile** [comment]
I hope you don't plan on making a new issue for every single line of code with an issue. If you really want to help, I would suggest making a pull request for all these things you find and proposed fixes. Making a new issue for every single line of code or variable isn't very productive. What I'm saying is, if you can go through all the code and take the time to make a new issue for all of them, its probably a lot faster on your end to just compile all the things you find into a pull request instead of spamming new issues for each individual line.

**Comment by volo-zyko** [comment]
Ok, no problem, I'll make a PR. I'm just getting acquainted with the code (and with the code maintainer along the way). I don't know what is the most appropriate way of action in this project yet. So, sorry for the hassle.

**Comment by lwvmobile** [comment]
Well, you'll quickly learn I am by no means an expert programmer, and some of the code you may see will be baffling on how ridiculous or broken it might be. Honestly, when I saw the last two issues, I had assumed this was some sort of troll or something lol. Anyways, just before you start working too hard on things, let me push a couple of small things and make a dev branch again, I get kind of paranoid about merging major changes into the main branch without thoroughly testing them.

**Comment by lwvmobile** [comment]
Okay, I pushed the few things I had to push and also made a new branch, so just do your PR on the ZDEV branch. Sorry, I should have had it all set up and ready to go before you started.

**Comment by volo-zyko** [comment]
Nothing can stop me now. :) I'll switch to ZDEV branch in my next PRs.

**Comment by lwvmobile** [comment]
Oh, I was going to mention, might be worth your time to stay out of the ysf.c file and probably trellis.c (the entire file is a mess, but it mortifies me thinking about trellis and convolutional decoding so much, I haven't ever gotten back around to cleaning it up or trying to fix it better), I'm working on Yaesu Fusion right now, so the ysf.c file is going to be changed pretty soon.

**Comment by volo-zyko** [comment]
Things change pretty fast. You've merged the code while I was juggling git branches. Just ignore my PR.

**Comment by lwvmobile** [comment]
Yeah, sorry about that. I was trying to stay ahead of the curve and ended up making a few mistakes with not pushing things before making a new branch, and then also not merging your PR before making the same new branch.

**Comment by lwvmobile** [comment]
Okay, I just merged the PR from earlier back into ZDev3, so now it SHOULD be equal.

**Comment by lwvmobile** [comment]
Just FYI, if you do any more work on the code, you might want to pull the latest ZDev3 branch and make sure to submit PR to that branch, and not main. I rebased the last PR and it doesn't seem to have caused any issues. I just don't want any of the work I've put up on YSF to get nuked on accident with a rouge git commit (I honestly still don't understand the entire voodoo of Git commands, aside from git stash and git stash apply and a few others.)

**Comment by volo-zyko** [comment]
Definitely, I will try to keep up with the latest ZDev3.

**Comment by lwvmobile** [comment]
Whatever changes you made to cleanup and exit won't allow the user to quit from the ncurses menu with the exit menu item or the 'q' key when using the rtl dongle as input: It was working before, and now it isn't.

```
Build Version:  v2.1-19-gb5d24f9 
MBElib Version: 1.3.2
Setting symbol rate to 9600 / second
Decoding only ProVoice frames.
Channel [00001] [851375000]
Channel [00002] [851800000]
Channel [00003] [855987500]
Channel [00004] [858487500]
Channel [00005] [852312500]
Enabling NCurses Terminal.
RTL Input: Dev 0 Freq 851000000 Gain 36 PPM -2 BW 24 SQ 100 UDP 0 
Audio In Device: rtl
Setting RTL PPM Error Set to -2
Setting RTL Bandwidth to 24000 Hz
Setting RTL RMS Squelch Level to 100
Found Rafael Micro R820T/2 tuner
Using RTLSDR Device Index: 0. 
Tuner gain set to 36.40 dB.
Tuner error set to -2 ppm.
 (Center Frequency: 851252000 Hz.) 
Oversampling input by: 42x.
Oversampling output by: 1x.
Buffer size: 8.13ms
Exact sample rate is: 1008000.009613 Hz
Allocating 15 zero-copy buffers
Sampling at 1008000 S/s.
Output at 24000 Hz.
Control Channel Signal Lost. Searching for Control Channel.
Tuning to Frequency: 851.375000 MHz
Control Channel Signal Lost. Searching for Control Channel.
Tuning to Frequency: 851.800000 MHz
13:50:56 Sync: +EDACS 
13:50:56 Sync: +EDACS 
13:50:57 Sync: +EDACS 
13:50:57 Sync: +EDACS  Adjacent Site [DB][219] on CC LCN [01]
13:50:57 Sync: +EDACS  Site ID [F3][243] Extended Addressing
13:50:57 Sync: +EDACS  Patch -- Site [144] Source [99] Target [1155] 
13:50:57 Sync: +EDACS  Control Channel LCN [2]
13:50:57 Sync: +EDACS  Adjacent Site [B5][181] on CC LCN [02]
13:50:57 Sync: +EDACS  Site ID [F3][243] Extended Addressing
13:50:57 Sync: +EDACS  Patch -- Site [40] Source [251] Target [21265] 
13:50:57 Sync: +EDACS  Control Channel LCN [2]
13:50:57 Sync: +EDACS  Adjacent Site [B1][177] on CC LCN [03]
13:50:57 Sync: +EDACS  Site ID [F3][243] Extended Addressing
13:50:58 Sync: +EDACS  Control Channel LCN [2]
cleaning up...

```

It get's stuck on `cleaning up...`

**Comment by volo-zyko** [comment]
I'll take a look on Monday. Ok? It could be that signal handlers are not set in this case...

**Comment by volo-zyko** [comment]
Or, the second thought, there is nothing to do with the handlers, as the quit is triggered by the user's action. I'll take a look what's done when 'q' is hit.
