### ISSUE TITLE
WIP: Yaesu Fusion Decoding

### ISSUE THREAD

**Issue by lwvmobile** [lwvmobile/dsd-fme#143]
Over a year later, and I have finally resumed working on YSF decoding after doing an initial setup for it and quitting after a day. Better late than never. I'll just keep it brief and go over what is currently working, and what currently isn't working.

**Working:** 
FICH Decode
DCH Decoding on Type 2, and Full Rate Data (HC, TC, and Data/TXT Blocks)
VeCH Type 2 Voice

**Not Working:**
Full Rate Voice (issue with FEC, PN Sequence, De-interleave,  Demodulation, or any combo of those)

**Not Tested:**
VCH Type 1 Voice  (No samples to test against)

Good news is, I think most YSF comms occur on Type 2, so if your local repeater only uses Type 2, then everything will work for you.

**Comment by lwvmobile** [comment]
Update: 

Full Rate Voice (Voice Wide) is working now. Turns out, mbelib likes to its Full Rate frames loaded backwards (Endianness) compared to the sane rational and logical way to approach it. I never really looked at that aspect before, but now that I see it, I can't help but to be slightly annoyed by why it was set up that way in mbelib and in the voice deinterleaving tables. Anyways, without rambling, I'll update my fixes shortly, may take a few extra moments to look at the data frames on Full Rate, make sure that's okay (getting CRC errors, so could just be a crummy sample, but its the only full rate sample I have)

**Comment by oe4ewa** [comment]
Yeah.

**Comment by lwvmobile** [comment]
> Yeah.

Try not to sound too enthusiastic about it lol.
