### ISSUE TITLE
Arch linux install guide.

### ISSUE THREAD

**Issue by dreamcoderuk** [lwvmobile/dsd-fme#153]
Looks like an amazing project I was just requesting a documentation guide for installing on arch linux or a build made and added to the arch aur.

Thank you

**Comment by lwvmobile** [comment]
Yeah, I'm afraid I really don't have a guide perse on building for arch, but what I've found is that you just have to find the equivalent packages to what I have listed for Debian/Ubuntu or Fedora and install those first, and then you should be able to compile. I do have some manual instructions for compiling, found [here](C2D9C4B3). You will also need to install the help2man program in Arch, which isn't listed as a dependency, but I've noticed on my own Arch system that its picky about it not being there and fails compiling at that step.

Just as another aside, though, what I found in the past as sort of a 'cheat' to easily have the dependencies (or most of them, minus the rtlsdr (rtl_fm) and codec2 support, but still be able to easily compile in Arch, is to install the LEH AUR version first, and that'll set up most all the dependencies for you, and then install the rest manually. [dsd-louiserigherve-git](https://aur.archlinux.org/packages/dsd-louiserigherve-git)

I've never really attempted to create an AUR package before however, and with shifting dependencies and Arch being Arch, I don't think I have the technical know how or patience to keep up with a random change that breaks a dependency. I'll let somebody else so inclined to make an AUR package to do so instead.

In the future, I'll try to get a base version of Arch on my VM and document the steps required to getting everything compiled from scratch. I use Arch myself (garuda) but even I couldn't tell you right away what all needs to be done to compile from scratch, other than to just work one dependency at a time until it compiles.

**Comment by lwvmobile** [comment]
Actually, here is the manual compilation instruction I already had, it seem the link I replied with was bad.

https://github.com/lwvmobile/dsd-fme/blob/main/examples/Install_Notes.md

**Comment by dreamcoderuk** [comment]
Thanks, I will have a go over the weekend and if manage it I will update this to share.

Thanks

**Comment by francisuk1989** [comment]
https://github.com/lwvmobile/dsd-fme/pull/160
I have created a auto script for Arch.

@lwvmobile This issue can be closed?

**Comment by lwvmobile** [comment]
Okay, I'm going to go ahead and close this issue now that we have the installer script and the install notes updated with an arch installation method.
