### ISSUE TITLE
RC4 KEY ISSUE

### ISSUE THREAD

**Issue by StartValve** [lwvmobile/dsd-fme#154]
Doing a test on P25 with RC4 HEX key where all the numbers are 0, I couldn't decode the audio.

**Comment by lwvmobile** [comment]
Do you mean to say you are using a key value of 0x0000000000 ?

**Comment by StartValve** [comment]
Yes!

**Comment by lwvmobile** [comment]
DSD-FME isn't coded to accept a value of 0 for the rc4 key, so if you are trying to use it as a key, then it won't be able to decode it. I didn't know a key value of 0 was a legitimate key value.

**Comment by StartValve** [comment]
Ok, I didn't know that DSD FME couldn't decode it, I was trying to decode it for testing. 0 is a key value that I use to do technical tests on my system, if you want to implement decoding in the future, I can send you audio samples. Thanks for your reply.

**Comment by lwvmobile** [comment]
Try with key value 10000000000 , noting the extra 0 on the end. DSD-FME will see that as a non-zero key value, but when it loads it, it should only load the zeroes since it truncates anything over FFFFFFFFFF and that may just work for you. I usually put a

**Comment by StartValve** [comment]
Greats, work perfectly!, Thanks :D

**Comment by lwvmobile** [comment]
Sounds good. Is that just p1, or p1 and p2?

**Comment by ahlawy81** [comment]
I have a lot of p1 recordings but AES 😁

**Comment by StartValve** [comment]
> Sounds good. Is that just p1, or p1 and p2?

Just P1, I have not system p2 on my area
