### ISSUE TITLE
AMBE DLL support

### ISSUE THREAD

**Issue by JOULTICOA** [lwvmobile/dsd-fme#155]
Hello,

Lot of potential DSD-FME user have access to official AMBE DLLs with the latest enhanced vocoder.

Would you be interested in adding support for these official AMBE DLLs?

They typically have file name "DvsiNative.dll"  and I can provide some example code to you privately that you can then adapt so it suitable for public

**Comment by WiredLife** [comment]
will this improve the voice quality? if so, please add it

**Comment by AsciiWolf** [comment]
Are these libraries also available for Linux or macOS?

**Comment by lwvmobile** [comment]
> Lot of potential DSD-FME user have access to official AMBE DLLs with the latest enhanced vocoder.
> 
> Would you be interested in adding support for these official AMBE DLLs?
> 
> They typically have file name "DvsiNative.dll" and I can provide some example code to you privately that you can then adapt so it suitable for public

I had left this open for quite a while, and never responded, but after contemplating this for some time, and the way that audio_work has shaped up, I am going to decline working on this issue, or supporting the native DLLs and the hardware dongle as well. I'm not saying that it would be a bad thing to have support for them, but there are several contributing factors to my decision not to add support for them. 

1. They aren't open source, so I can't see what's in them and while I'm sure they are fine, I'd like to steer away from using or supporting things that don't have source code.

2. I am not sure about how DVSI would feel about me supporting them. They seem to be okay with the open source MBElib and dsd, as in, its been up for a decade now and nobody has ever shut it down, so I'd rather leave a good thing be.

3. With the way audio_work has shaped up, and this also goes for including the hardware dongle support, I don't really know if I can maintain two or three separate ways of handling audio to make different things work, and I also don't want to put myself (again, I'm just one person) under the stress of having to maintain two or three different implementations to get the same decoded audio, while I will personally admit that the decoded audio from official stuff would probably work better, that's still three times the work load, and I would like to get to a state where I can just simply maintain and coast for an extended period of time without constantly adding new things and fixing new things.
