### ISSUE TITLE
DMR T3 Control Channel Windows OS Issue?

### ISSUE THREAD

**Issue by francisuk1989** [lwvmobile/dsd-fme#156]
I am trying DMR T3 Trunking but having issues but it could be my error on my part.

`dsd-fme -fs -i tcp -U 4532 -T -C DMRT3CH.csv -G DT3TGS.csv -N 2> log.ans`

The DMR T3 Control Channel is on 555.531250 but is skipping? Also using SDR++

DMRT3CH.csv file

```
ChannelNumber(dec),frequency(Hz) (do not delete this line or won't import properly)
803,555531250,default cc <<< i have also tried without default cc
812,555643750
826,555756250
821.555762500
830,555868750
840,555993750
850,556118750
857,556206250
867,556331250
```

```
Build Version: v2.1b (20230714)
MBElib Version: 1.3.2
Channel [00803] [555531250]
Channel [00812] [555643750]
Channel [00826] [555756250]
Channel [00830] [555868750]
Channel [00850] [556118750]
Channel [00867] [556331250]
8004, A, Traffic Control Unit 
Control Channel Signal Lost. Searching for Control Channel.
Tuning to Frequency: 555.531250 MHz
Control Channel Signal Lost. Searching for Control Channel.
Tuning to Frequency: 555.643750 MHz
Control Channel Signal Lost. Searching for Control Channel.
Tuning to Frequency: 555.756250 MHz
```

**Comment by francisuk1989** [comment]
Hmmm, I have tried with a Linux (Manjaro) what is Arch based and is working great!
I think there is a issue with WIndows, I did check my windows firewall and disabled it completely but no joy.

**Comment by francisuk1989** [comment]
I have tried with a Linux (Manjaro https://manjaro.org) what is Arch based and is working great!

I think there is a issue with WIndows, I did check my windows firewall and disabled it completely but no joy.

Ill close this issue as is not dsd fme related, Just Windows.

**Comment by lwvmobile** [comment]
Just to follow up on this, but in Windows was there any positive or negative indication that DSD-FME connected to the TCP Sink and RIGCTL Server in SDR++. I have had a few people tell me they needed to manually specify the local host address 127.0.0.1 instead of using localhost inside of SDR++ and also needed to use dsd-fme like this. 

`dsd-fme -i tcp:127.0.0.1:7355 -U 4532 -T`

before it would connect and start working correctly.
