### ISSUE TITLE
DMR T3 Not showing active channels but only one system works

### ISSUE THREAD

**Issue by francisuk1989** [lwvmobile/dsd-fme#157]
I have come cross 3 different DMR T 3 site from the same company, They are maybe using some sort of IP based system to extend is coverage however nothing is shown on the control channels and just shows

I have see Voice or Data channels been used from the system but it just shows the following in green, This happens to 3 sites by the same company and i can also comfium that another company what is a smaller one is doing the same.

Sorry for the confusion but is different companies that im having issues with, Only one company works.

```
--Call Info-------------------------------------------------------------------
| DMR BS - DCC: [13]  TIII - Large 2-1.14
| SLOT 1 - TGT: [       0] SRC: [       0]                       | CSBK
| V XTRA |
| D XTRA |
| SLOT 2 - TGT: [       0] SRC: [       0]                       | CSBK
| V XTRA |
| D XTRA |
```
However i can confirm there is another system that is working fine and shows the active control channel as below.

```
--Call Info-------------------------------------------------------------------
| DMR BS - DCC: [00]  TIII - Small 1-1.2
| SLOT 1 - TGT: [       0] SRC: [       0]                       | CSBK
| V XTRA |
| D XTRA |
| SLOT 2 - TGT: [       0] SRC: [       0]                       | IDLE
| V XTRA |
| D XTRA |
|        | Active Group Ch: 857 TG: 37; Active Group Ch: 850 TG: 3
```

**Comment by lwvmobile** [comment]
To get any more information on that upper system I'd have to see the output of the console in the log file (log.ans) if you have it. Could be RAS protected, or could be it needs different channels mapped in as frequencies, or it could just be that it isn't very busy at all. If you see a lot of CRC ERR messages attached to those CSBK's, then it most likely is RAS protected, which can be bypassed with the -F option. If its decoding the CSBKs okay, and you see channel grants in them, then it most likely needs proper channels mapped in via the csv file.

**Comment by francisuk1989** [comment]
Hi @lwvmobile

1) I have looked up the license for the company and is allocated to have 8 freqs including the control channel, when is busy i can see the channels active with Voice and i can hear/see the info and listen to the voice channel without the option "-F" possible RAS protected but not sure

DSDPlus (not the fast line) is showing is RAS on other Tier 2 sites but dont have to use the option "-F" to "listen"

2)
I can confium from another system, trunking works fine and mapped the channels in via the csv file fine.

i have attach a recorded input for you to inspect whenever you have time.

`https://transfer.sh/btPyT9eTG8/dsdrec.zip`

**Comment by francisuk1989** [comment]
> To get any more information on that upper system I'd have to see the output of the console in the log file (log.ans) if you have it. Could be RAS protected, or could be it needs different channels mapped in as frequencies, or it could just be that it isn't very busy at all. If you see a lot of CRC ERR messages attached to those CSBK's, then it most likely is RAS protected, which can be bypassed with the -F option. If its decoding the CSBKs okay, and you see channel grants in them, then it most likely needs proper channels mapped in via the csv file.

Thanks, Using option "-F" works, Its shown now as CapMax+

**Comment by francisuk1989** [comment]
> To get any more information on that upper system I'd have to see the output of the console in the log file (log.ans) if you have it. Could be RAS protected, or could be it needs different channels mapped in as frequencies, or it could just be that it isn't very busy at all. If you see a lot of CRC ERR messages attached to those CSBK's, then it most likely is RAS protected, which can be bypassed with the -F option. If its decoding the CSBKs okay, and you see channel grants in them, then it most likely needs proper channels mapped in via the csv file.

Thanks, Using works, Its shown now as `CapMax+`

**Comment by lwvmobile** [comment]
Just as a note though, on the wav file for Company 2, pretty sure that isn't RAS, its just bad or weak signal.

**Comment by lwvmobile** [comment]
Also, RAS is a form of CRC checksum manipulation whereas the CRC is changed so that outsiders listening get a bad checksum value. Radios usually can't properly decode those because of the CRC errors, but software can usually just bypass it if desired.

**Comment by francisuk1989** [comment]
@lwvmobile 
On two sites for DMR T3, no manufacturer is show like `Mototolla CapMax+`. Even with the option -F it still dont show. However listening to the control channel, i can see active channels passing by so that no issue there.

The system is a `Tait`

Samples from SDR++
`https://transfer.sh/OmObUUpiaO/uni_sys.zip`

**Comment by lwvmobile** [comment]
On a few Tait systems I've observed as well, its very seldom that it'll pass a CSBK that has the FID set as a Tait specific one (0x58). I think that is really dependent on the site in particular and if it has to address radios specifically with that MFID set or not. Often times for TIII, They seem to operate in the standard FID of 0x00. Its usually not until the radios start talking that you can catch some Tait specific Link Control FIDs and guess that it is a Tait system. Its also possible at times, that the system itself is not a Tait system, but that the radio talking is a Tait radio. If my understanding is correct, Tait is making it so that their equipment is more universally compatible with other system vendors.

```
18:26:47 Sync: +DMR  [slot1]  slot2  | Color Code=00 | CSBK
 C_ALOHA_SYS_PARMS - Small - Net ID: 1 Site ID: 1.2 Cat: AB
  Reg Req: 1 V: 2 Mask: 00 MS: 0
 DMR PDU Payload [99][00][09][01][F8][40][07][00][00][00][32][25] <---the second byte is 00
18:26:47 Sync: +DMR   slot1  [slot2] | Color Code=00 | IDLE 
18:26:47 Sync: +DMR  [slot1]  slot2  | Color Code=00 | CSBK
 C_ALOHA_SYS_PARMS - Small - Net ID: 1 Site ID: 1.2 Cat: AB
  Reg Req: 1 V: 2 Mask: 00 MS: 0
 DMR PDU Payload [99][00][09][01][F8][40][07][00][00][00][32][25]
18:26:47 Sync: +DMR   slot1  [slot2] | Color Code=00 | IDLE 
 SLC_C_SYS_PARMS - Small - Net ID: 1 Site ID: 1.2 - Reg Req: 1 - CSC: 68 
 SLCO Completed Block [24][00][64][40][F0]

```

Also, worht noting, on the Tait system, its not RAS enabled (that's Motorola specific) so no need for the -F bypass. I only recommend that on RAS enabled systems, otherwise it may give you false decodes on CSBKs and so on.

On the other hand, Motorola Capacity Max passes nearly every single FID as its own 0x10, so I just deduce that on DMR TIII, if that byte is set to 0x10, then it is Capacity Max, which seems to be the prime give away that it is CapMax and not a standard DMR TIII system.

```
18:33:21 Sync: +DMR   slot1  [slot2] | Color Code=12 | CSBK
 C_ALOHA_SYS_PARMS - Large - Net ID: 1 Site ID: 1 Cat: A 
  Reg Req: 1 V: 2 Mask: 00 MS: 0 Capacity Max  -RAS 4 <--reserved BPTC bit is flagged on so RAS enabled
 DMR PDU Payload [99][10][09][00][F6][84][05][00][00][00][16][A3] <--second byte is 0x10, so motorola 
 SLC_C_SYS_PARMS - Large - Net ID: 1 Site ID: 1 - Reg Req: 1 - Capacity Max 
 SLCO Completed Block [28][40][60][0F][20]

18:33:21 Sync: +DMR  [slot1]  slot2  | Color Code=12 | CSBK -RAS 4 
 DMR PDU Payload [A2][10][00][E0][00][24][00][00][00][00][FE][A9]
18:33:21 Sync: +DMR   slot1  [slot2] | Color Code=12 | CSBK
 C_ALOHA_SYS_PARMS - Large - Net ID: 1 Site ID: 1 Cat: A 
  Reg Req: 1 V: 2 Mask: 00 MS: 0 Capacity Max  -RAS 4 
 DMR PDU Payload [99][10][09][00][F6][84][05][00][00][00][16][A3]
18:33:21 Sync: +DMR  [slot1]  slot2  | Color Code=12 | CSBK -RAS 4 
 DMR PDU Payload [A2][10][00][E0][00][24][00][00][00][00][FE][A9]
18:33:21 Sync: +DMR   slot1  [slot2] | Color Code=12 | CSBK
 C_ALOHA_SYS_PARMS - Large - Net ID: 1 Site ID: 1 Cat: A 
  Reg Req: 1 V: 2 Mask: 00 MS: 0 Capacity Max  -RAS 4 
 DMR PDU Payload [99][10][09][00][F6][84][05][00][00][00][16][A3]
 SLC_C_SYS_PARMS - Large - Net ID: 1 Site ID: 1 - Reg Req: 1 - Capacity Max 
 SLCO Completed Block [28][40][60][0F][20]

```

**Comment by francisuk1989** [comment]
> Also, worht noting, on the Tait system, its not RAS enabled (that's Motorola specific) so no need for the -F bypass. I only recommend that on RAS enabled systems, otherwise it may give you false decodes on CSBKs and so on.

Thanks again for that information, I learn something new everyday,

I just thought it might of been a case of "missing IDs to ID the system"

> Its also possible at times, that the system itself is not a Tait system, but that the radio talking is a Tait radio. If my understanding is correct, Tait is making it so that their equipment is more universally compatible with other system vendors.

Far as i know, From a case study, Its 100% a Tait system or i would of said "im not sure what system it is" 👍
