### ISSUE TITLE
rtl_tcp support

### ISSUE THREAD

**Issue by francisuk1989** [lwvmobile/dsd-fme#158]
Please could you add support for rtl_tcp,

Its supported on small OpenWrt router's and since is Linux both ARM64/x86_64 is supported, It also can be run on any cheap devices with a nice 100 meters of cat6e ethernet. 😃 

```
root@router1:~# rtl_tcp -h

Use the device argument 'rtl_tcp=192.168.1.1:1234' in OsmoSDR (gr-osmosdr) source
to receive samples in GRC and control rtl_tcp parameters (frequency, gain, ...).

rtl_tcp, an I/Q spectrum server for RTL2832 based DVB-T receivers
Usage:  [-a listen address]
        [-p listen port (default: 1234)]
        [-f frequency to tune to [Hz]]
        [-g gain (default: 0 for auto)]
        [-s samplerate in Hz (default: 2048000 Hz)]
        [-b number of buffers (default: 15, set by library)]
        [-n max number of linked list buffers to keep (default: 500)]
        [-d device index (default: 0)]
        [-P ppm_error (default: 0)]
        [-T enable bias-T on GPIO PIN 0 (works for rtl-sdr.com v3 dongles
```

i think for a simple commad would look like .... unless anybody knows any tweaks?

rtl_tcp -a 192.168.1.1 (<< Open rtl-tcp on the device first) and then via dsd-fme
`dsd-fme -fs -i rtl_tcp -a 192.168.1.1 -f 467.1M -s 2400000`

unfortunately rtl_udp is not support via OpenWrt and only rtl_tcp
https://github.com/openwrt/packages/tree/master/utils/rtl-sdr/files
however i can see Arch and Ubuntu has rtl_udp
https://archlinux.org/packages/extra/x86_64/rtl-sdr/

**Comment by axpe95** [comment]
You can demod the IQ data with https://github.com/ha7ilm/csdr; after pipe the output to dsd-fme
