### ISSUE TITLE
WAV file from GQRX not working

### ISSUE THREAD

**Issue by iz4tow** [lwvmobile/dsd-fme#162]
Good evening,
I'm trying to use dsd-fme with recorded tracks from GQRX (wav 48K/1C) but it seems it not works.

The command I'm using is:
`dsd-fme -i test.wav -b 1` (the track is with BP)

The result is:
```
            Digital Speech Decoder: Florida Man Edition
 ██████╗  ██████╗██████╗     ███████╗███╗   ███╗███████╗
 ██╔══██╗██╔════╝██╔══██╗    ██╔════╝████╗ ████║██╔════╝
 ██║  ██║╚█████╗ ██║  ██║    █████╗  ██╔████╔██║█████╗  
 ██║  ██║ ╚═══██╗██║  ██║    ██╔══╝  ██║╚██╔╝██║██╔══╝  
 ██████╔╝██████╔╝██████╔╝    ██║     ██║ ╚═╝ ██║███████╗
 ╚═════╝ ╚═════╝ ╚═════╝     ╚═╝     ╚═╝     ╚═╝╚══════╝
Build Version:  2.1b-29-g7b3a257 
MBElib Version: 1.3.2
CODEC2 Support Enabled
Audio In Device: test.wav

End of test.wav

Total audio errors: 0
Total header errors: 0
Total irrecoverable header errors: 0
Exiting.
```

If I play the track and pipe it with Pulse it works, so is not the track the problem.
In this case with the simple command `dsd-fme -b 1` and playing the track on the virtualsink.

**Comment by lwvmobile** [comment]
Try running it with `dsd-fme -fs -b 1 -i test.wav -s 96000` and see if that works. I just opened GQRX and did a quick recording, and found the default settings for wav files on the version I have is to create a 48k/2ch stereo wav file, and the -s 96000 'should' be able to run 48k/2 files mostly.

Also, worth noting, some system types (Particularly NXDN and DMR Simplex) don't always do so well when the wav file is fed directly into DSD-FME, the decoding will usually have more errors than just playing the file back through a media player and a virtual sink.

**Comment by iz4tow** [comment]
Yes true....I'm checking too, It's a 2C not 1C, very strange and a nonsense... 
Ok deleting the RC before using DSD-FME works
