### ISSUE TITLE
Improvement: LRRP 

### ISSUE THREAD

**Issue by Yorch23** [lwvmobile/dsd-fme#164]
Hello
First of all, thank you for the work, I really enjoy dsd-fme.
One of the received networks sends LRRP position, when exploring the DSDPlus.LRRP file I find "2023/08/31 22:17:26 14008710".

Greetings.

**Comment by t4z21** [comment]
> Hello First of all, thank you for the work, I really enjoy dsd-fme. One of the received networks sends LRRP position, when exploring the DSDPlus.LRRP file I find "2023/08/31 22:17:26 14008710".
> 
> Greetings.

Hi, I have just got dsd-fme up and running audio and so on comes through fine, I am wondering how do I load up LRRP and I cannot find the DSDPlus.LRRP file anywhere ? I set it to save as file DSDPlus.LRRP but I'm not finding the file anywhere is the dsd-fme directory? Can you help me when I used dad fast lane it was easy am I doing something wrong or is LRRP not included with dsd-fme. Thanks 😊😊

**Comment by lwvmobile** [comment]
> One of the received networks sends LRRP position, when exploring the DSDPlus.LRRP file I find "2023/08/31 22:17:26 14008710".

If you get that without any more information, then for whatever reason, it decided that there wasn't any LRRP information in that message block. Probably is ARS or something else though. I need to tighten up the code on that part so it doesn't put just a date/time/RID in there unless its LRRP.



> Hi, I have just got dsd-fme up and running audio and so on comes through fine, I am wondering how do I load up LRRP and I cannot find the DSDPlus.LRRP file anywhere ? I set it to save as file DSDPlus.LRRP but I'm not finding the file anywhere is the dsd-fme directory? Can you help me when I used dsd fast lane it was easy am I doing something wrong or is LRRP not included with dsd-fme. Thanks 😊😊
> 
> I have enabled toggle payloads to console, IV set it to save file as DSDPlus.LRRP but I'm not yet seeing it in the home folder or anything (I read some of the closed help threads.) Maybe I'll wait for some more GPS data to come thru and it's might save the file now. It's saving wave files and created the folder for that. GPS data was coming thru via DSTAR just it has not been creating the .LRRP file in the home folder... Ill update once more DSTAR with GPS comes through. Thanks loving the DSD-FME only came across it yesterday good work.

Currently, LRRP is only coded and working (partially working) for DMR systems, I don't have anything in place to plot any other system type GPS related data, including DSTAR. Actually, unless you are using the audio work branch (or the precompiled dsd-fme-aw.exe) file, then the extended DSTAR slow data won't even be decoded. Even then, its not deinterleaved properly yet, so if you see and GPS information, its all jumbled up with other information. I got frustrated with that interleave and lack of OPcode for the data present so I just dump it raw into the console, no attempt to decombobulate the DSTAR slow data when its jumbled up.

So, at best, for now, its just going to look like this:

```
23:38:58 Sync: -DSTAR VOICE   RPT 2: DL1ESZ G RPT 1: DL1ESZ B DST: CQCQCQ   SRC: DL1ESZ  6072 REPEATER
23:38:58 Sync: -DSTAR VOICE   RPT 2: DL1ESZ G RPT 1: DL1ESZ B DST: CQCQCQ   SRC: DL1ESZ  6072 REPEATER
23:38:59 Sync: -DSTAR VOICE   RPT 2: DL1ESZ G RPT 1: DL1ESZ B DST: CQCQCQ   SRC: DL1ESZ  6072 REPEATER
23:38:59 Sync: -DSTAR VOICE   DATA: $CRCACD5,DL1ESZ>API51,DSTAR*:!5117.69N/00649.56E           
23:39:00 Sync: -DSTAR VOICE   DATA: E-Bike 
```

You'll see the one line that has jumbled Text and GPS, its kind of annoying.

**Comment by lwvmobile** [comment]
If nobody has any follow up questions, concerns, etc on this issue, then I'm going to go ahead and close it in a few days.

**Comment by Dmedia3412** [comment]
Looks like DSheirer /sdrtrunk has implemented P25 Location and it works well. You can see how he did it https://github.com/DSheirer/sdrtrunk/commit/a0d6950c754ff6ac7d8e536ff032ad2402724b49

![GPS](https://github.com/lwvmobile/dsd-fme/assets/93947899/bdd158ae-6fa5-4880-9fd0-308f8341f05f)

**Comment by lwvmobile** [comment]
Okay, I'll try to look into it when I have some time. At a quick glance, it looks like the layout is the same as DMR's Embedded GPS format for link control. I'll have to try to find some samples of a system that I have that may have that opcode, I don't think I've noticed it before if it has been present.
