### ISSUE TITLE
Per Call .wav name

### ISSUE THREAD

**Issue by Dmedia3412** [lwvmobile/dsd-fme#168]
You can correct the name Per Call .wav
remove special characters from date and time?

from 2023-10-17 230038 CC 1 - TG 1234 - RD 1234567

for example on
YYYYMMMDD HHMMSS

20231017 230008 CC 1 - TG 1234 - RD 1234567

This will allow you to correctly use the recordings with rdio scanner.

**Comment by lwvmobile** [comment]
Yeah, that's an odd side effect that occurs in Cygwin, I've tried fixing it before (I thought it was fixed previously). I'll have to look into it again when I have a chance and figure out why it does that in Windows (it doesn't do that in Linux).

**Comment by Dmedia3412** [comment]
Yes, that's right, this effect on Windows.
I'm using WIN10 22H2

**Comment by lwvmobile** [comment]
Here, give this patch a try, see how it does. I've addressed both the time/date situation to remove any colons (or random characters) in Windows, and also added the opcode for the MFID90 GPS on P25p1, but I ran it against multiple systems and samples I had, and didn't find a single one that carried that opcode, and I honestly have no idea if the calculations for lat and lon are correct or not.

[dsd-fme-aw223-20231024-patch.zip](https://github.com/lwvmobile/dsd-fme/files/13125493/dsd-fme-aw223-20231024-patch.zip)

**Comment by Dmedia3412** [comment]
Can I send you a sample recording personally by email?

The longitude seems correct but the latitude does not.

**Comment by lwvmobile** [comment]
Just message me on RR if you need to

Meanwhile, I'll double check the long and lat calculations. It could be off due to hemisphere/quadrant of the earth you are decoding.

**Comment by Dmedia3412** [comment]
There is another problem in the file name, sometimes MS appears but these are not direct calls.
Or did I misunderstand their meaning?

20231214 165659 MS - CC 1 - TG xxxxx - RD xxxxxxx

The Rdio-scanner template simply skips them.

**Comment by lwvmobile** [comment]
MS should be for DMR Simplex, but very occasionally, any signal may randomly sync as DMR MS, so its best not to use any sort of AUTO mode if possible to avoid those things.

**Comment by Dmedia3412** [comment]
Which variable should I use so that FME doesn't get confused?

Now I use -fs for DMR, all calls go exclusively through the repeater.
