### ISSUE TITLE
Last data received frozen

### ISSUE THREAD

**Issue by Yorch23** [lwvmobile/dsd-fme#174]
Hello, would it be possible to keep the last data/voice received on the call screen, in dark color, until receiving a new voice/data call?
In the same way that the color code is maintained.
Thank you.

**Comment by lwvmobile** [comment]
I had at various points in time had the tgt/src data remain on screen (not zeroed out) until the next call comes in, but for various reasons, its been changed to zero out when the frame sync is lost. If I change things to keep it there until the next time, it'll probably undo some fix or some thing that I specifically had that required it to be zeroed out. It was probably something to do with call history and/or per call wav files, or similar.

**Comment by lwvmobile** [comment]
Oh, just noticed you said Data Call. I'll have to look at the code sometime and see if there is anything that will preserve it, but to be honest, I think I tried that out as well, and it lead to the data call being up for hours, even if no other activity occurred, and with no logging on it, I would confuse me as to exactly how old it was. Pretty sure it just goes away when frame sync is lost, and if not, then its on a short timer. Probably the former.

**Comment by lwvmobile** [comment]
Anywho, if I recall correctly from past issues you've chimed in on, you use the Windows version, correct? If so, try this patched exe file, I've disabled the zeroing out of voice call tgt/src and the data call strings so it'll persist forever. Maybe this will work for you for now. Just copy and paste that into the dsd-fme folder and change any bat files to call that exe by name instead.

[dsd-fme-aw256y-20231121-patch.zip](https://github.com/lwvmobile/dsd-fme/files/13432043/dsd-fme-aw256y-20231121-patch.zip)

Its probably not going to be a part of the regular code, but instead I'll upload the changes as a standalone patch file for the source code for future releases and let users decide whether or not they want to apply the patch if they build it themselves.

**Comment by Yorch23** [comment]
Hello, testing the change and keeping the data correct, it is working very well since it shows the last communication in the corresponding slot.

As a suggestion, could the last data be deleted when receiving a different color code?
Now it maintains the last Talk Group and SRC, but when receiving call data from another frequency with a different color code it still maintains TGT and SRC from another different frequency (network).
![test_dsd_fme](https://github.com/lwvmobile/dsd-fme/assets/118568024/87ec111a-2e5c-4bc7-9944-3e64312d75d5)

Thanks, good job!

**Comment by Yorch23** [comment]
I work with Windows and Linux in a virtual machine, I currently have a launcher for DSD-FME in the form of a plugin for SDRSharp.
![sdrsharp1900](https://github.com/lwvmobile/dsd-fme/assets/118568024/06c84e85-ec27-44d6-ad57-e25a686a8e5d)

Greetings.

**Comment by lwvmobile** [comment]
> As a suggestion, could the last data be deleted when receiving a different color code?

I'll add it to the patch and post an update next time I generate an exe file for it. 

> I work with Windows and Linux in a virtual machine, I currently have a launcher for DSD-FME in the form of a plugin for SDRSharp.

Plugin looks pretty good. I would imagine quite a few people would be interested in having one similar for themselves. Does it just launch DSD-FME externally for you with specific CLI switches?

**Comment by Yorch23** [comment]
ok I will be attentive to the next publication and we will continue commenting, thank you.

Taking advantage of the fact that the plugin code for sdrsharp was published in Visual Studio, it was just adding a launcher for the .bat

**Comment by lwvmobile** [comment]
Alright, I just went ahead and generated another exe file for you where it will only zero out if the color code changes since it was only a few extra lines of code and nothing extravagant, probably took longer to get the VM going and compile it that it did to copy and paste a few lines around. 

[dsd-fme-aw261y-20231122-patch.zip](https://github.com/lwvmobile/dsd-fme/files/13444703/dsd-fme-aw261y-20231122-patch.zip)

Other than that though, any further work on it will probably have to come in the future when I have a chance to re-write the entire call history part, and that is going to be a bigger overhaul, and I'm not eager to start working on it. This is semi linked in nature to #171 #172 and #173 as well, since the code would overhaul all of those issues, so I'll probably close down all issues regarding the call history and src/tgt values and per call wav files. Its planned, just not going to happen overnight or probably not for the remainder of the year if I'm honest.

**Comment by Yorch23** [comment]
Thank you, it works perfect, I keep PDU data and delete it when I receive a new CRC freq with a different color code.
Great job!!

**Comment by lwvmobile** [comment]
Alright, good to hear, I'm going to go ahead and close this as complete, but bearing in mind a more comprehensive overhaul is still going to occur one day, one of these days, eventually.
