### ISSUE TITLE
main branch removed

### ISSUE THREAD

**Issue by ZeroChaos-** [lwvmobile/dsd-fme#180]
Not a problem, just asking if it's intentional.  The main branch of git was removed and the default branch is now audio_work.  This is unusually enough that I just wanted to check.

**Comment by lwvmobile** [comment]
'main' was renamed to v2.1b-final and 'audio_work' became the default branch. Yes, it was intentional, no, it is not unusual for me to change/rename branches.

**Comment by ZeroChaos-** [comment]
thank you for the clarification
