### ISSUE TITLE
[Feature req DMR] Displaying logical-physical channel C_BCAST MBC PDU content

### ISSUE THREAD

**Issue by kantooon** [lwvmobile/dsd-fme#182]
I'm trying to debug the broadcast of site logical-physical channel announcements.
These things:

12:30:12 Sync: +DMR  [slot1]  slot2  | Color Code=01 | MBCH
12:30:12 Sync: +DMR   slot1  [SLOT2] | Color Code=01 | VC6 
 SLOT 2 TGT=1496773 SRC=2265019 Group Call  
12:30:12 Sync: +DMR  [slot1]  slot2  | Color Code=01 | MBCC
 Announcements (C_BCAST) Announce Logical Channel/Frequency Relationship (Chan_Freq)                                                                                 
 SLC_C_SYS_PARMS - Tiny - Net ID: 2 Site ID: 1.2 - Reg Req: 1 - CSC: 1 

Do you think it's possible to display the content? SDRTrunk shows me these come with a colour code of 0 which would be a bug somewhere deep in my code. If possible I'd like to confirm this with dsd-fme.
Also, I don't know if this is implemented or not, but it would be cool if dsd-fme would populate its channel map from these broadcasts.

**Comment by lwvmobile** [comment]
If you just want to dump the payload, you can use the `-Z` option and it'll show you the payload for each of those. If you need decoding done of those, perhaps I'll put it on my todo list. I seem to recall looking at the same PDU for channel numbering and frequency information in the past, but didn't have much luck. I think its also a thing where some of these CSBK/MBC messages aren't entirely the same thing on Motorola CapMax vs Standard Implementations. If you ever notice the Category A/B/AB values and the CSC values (common slot counter) on CapMax, they do not work the same way as they do in Standard, so they probably are used for other things.

Also, of note, if that system has MBC header and continuation blocks, then usually on Tier 3, you don't need a channel map, the call grants will contain enough information to pump out a frequency without a user csv file.
![Screenshot from 2022-11-24 20-42-28](https://github.com/lwvmobile/dsd-fme/assets/59371473/7306a418-032f-4d09-8ad2-7bc3bcf848eb)

![Screenshot from 2022-11-24 21-00-00](https://github.com/lwvmobile/dsd-fme/assets/59371473/a3b1b72f-4c70-4fde-b06f-f7207aab42c5)


Here is a snippet from a Hytera T3 system with absolute voice call grants.

```
13:47:20 Sync: +DMR  [slot1]  slot2  | Color Code=03 | MBCH
 DMR PDU Payload [31][00][FF][FC][66][13][95][66][63][00][4B][2E]
13:47:20 Sync: +DMR   slot1  [slot2] | Color Code=03 | CSBK
 DMR PDU Payload [BE][68][21][00][66][5B][CA][FF][FE][CA][B0][F0]
13:47:20 Sync: +DMR  [slot1]  slot2  | Color Code=03 | MBCC
 Talkgroup Voice Channel Grant (TV_GRANT) - Absolute
  LPCN: 4095; TS: 2; LPCN+TS: 8192; Target: 06689685 - Source: 06710016 
  RX ABS LPCN: 0229; RX INT: 452; RX STEP: 6800;
  Frequency: 452.850000 MHz
 Slot 1 - Multi Block Control Message
  3100FFFC6613956663004B2E
  B10300395C9D48389A900955

```

```
13:53:17 Sync: +DMR  [slot1]  slot2  | Color Code=03 | MBCH
 DMR PDU Payload [31][00][FF][F4][66][19][C9][66][78][58][A0][50]
13:53:17 Sync: +DMR   slot1  [slot2] | Color Code=03 | IDLE 
13:53:17 Sync: +DMR  [slot1]  slot2  | Color Code=03 | MBCC
 Talkgroup Voice Channel Grant (TV_GRANT) - Absolute
  LPCN: 4095; TS: 1; LPCN+TS: 8191; Target: 06691273 - Source: 06715480 
  RX ABS LPCN: 0111; RX INT: 451; RX STEP: 3000;
  Frequency: 451.375000 MHz
 Slot 1 - Multi Block Control Message
  3100FFF46619C9667858A050
  B103001BDC85DC386BB85CE3
```

A lot of other info (like Adjacent Sites) are also carried in MBC blocks, so those could also carry frequencies. I started looking into it once, but never got around to getting much, as I only have one sample that does this, and the recording has poor signal and tons of errors in decoding it.

```
13:47:21 Sync: +DMR  [slot1]  slot2  | Color Code=03 | MBCH
 DMR PDU Payload [28][00][35][80][96][B0][0F][E4][0F][FF][48][22]
13:47:21 Sync: +DMR   slot1  [slot2] | Color Code=03 | CSBK
 DMR PDU Payload [BE][68][21][00][66][79][B9][FF][FE][CA][25][6E]
13:47:21 Sync: +DMR  [slot1]  slot2  | Color Code=03 | MBCC
 Announcements (C_BCAST) Adjacent Site Information (Adjacent_Site)
 Slot 1 - Multi Block Control Message
  2800358096B00FE40FFF4822
  A80000ED9D2D7A39BAF41CFA

```

```
13:47:22 Sync: +DMR  [slot1]  slot2  | Color Code=03 | MBCH
 DMR PDU Payload [28][00][35][80][56][B0][0F][E4][0F][FF][F6][12]
13:47:22 Sync: +DMR   slot1  [slot2] | Color Code=03 | CSBK
 DMR PDU Payload [BE][68][21][00][66][5E][5A][FF][FE][CA][55][38]
13:47:22 Sync: +DMR  [slot1]  slot2  | Color Code=03 | MBCC
 Announcements (C_BCAST) Adjacent Site Information (Adjacent_Site)
 Slot 1 - Multi Block Control Message
  2800358056B00FE40FFFF612
  A80000161C815E3862BCD74F

```



I just also remember, on systems where I've seen the ` Announcements (C_BCAST) Announce Logical Channel/Frequency Relationship (Chan_Freq)` , the message is so infrequent, it wouldn't be very good at updating a channel values with frequencies. Its not like P25 where Channel Identifier Updates are constantly pumped out and you can use those to calculate any frequency value from a channel number.

I do believe there is a method to calculate channel frequencies in Tier 3, but it has to be the 'fixed' channel system and not the 'flexible' channel system, and also requires the user to preselect or cycle through BW or step values, as those aren't on the air, unless its in that PDU. The ETSI manual didn't seem to clarify these matters that I recall, but maybe I just missed it, one of those things that require me to open the PDU three times, and have it set on different pages to follow the flow.

ETSI TS 102 361-4 V1.12.1 (2023-07)
Annex C (informative):
Physical Channel Plan

**Comment by kantooon** [comment]
Thanks for the detailed reply, I'll try using the -Z option to dump the payload and check it. 
To be honest, I didn't know how logical-physical channel frequency relationship announcements were used in a real production system and that they are rarely broadcast. I figured they would be useful to build a complete frequencies map of the system for the listener.  (this is mostly from the perspective of amateur radio where you want to get all this info out to listeners)

Absolute channel grants do have the frequency information, but if the system is not at full capacity some RF channels at the end of the pool might go unnoticed since they don't get a grant very frequently.

For the fixed channel plan, I think both the site and the user terminal must have the same base frequency and step set up. So it's not possible to deduce 100% just from the channel grants what the real frequencies are. On the other hand, using absolute channel grants increases a bit the call setup time since the radio needs at least 120 ms to decode the MBC header and MBC continuation.

Anyway, if you do find it possible in the future to implement these broadcast PDUs, feel free to reopen this ticket so I can give it a spin.

**Comment by lwvmobile** [comment]
> For the fixed channel plan, I think both the site and the user terminal must have the same base frequency and step set up. So it's not possible to deduce 100% just from the channel grants what the real frequencies are.

There is a way to figure it out, but it requires knowing at least one frequency / channel pair and then you can work backwards to get the frequency base integer value, but you have to assume the step value, and may need to try multiple tries to get it. As far as doing it in real time with the software, I decided against trying to do it previously, as it would require user intervention to cycle step values if it weren't correct, and even then, the system could be using the 'flexible' plan which is usually just something like channel 1,2,3,4,5,6, etc and the frequencies just jump all over, its probably used more often in places where you have replaced an older system with a Tier 3 system and already had licensed those frequencies and just need to reuse them for a new system. Not to mention, its usually not too hard to just use SDR software to look for frequencies as they become active and map them out that way.

**Comment by lwvmobile** [comment]
TODO: Decode Announcements (C_BCAST) CSBK/MBC PDUs

**Comment by lwvmobile** [comment]
Can you send samples with Chan_Freq in it?

**Comment by lwvmobile** [comment]
Also, on your homebrew DMR site, is your net/site id set to 1-1.2, or is it supposed to be 0-0.1? Or something else. I had been adding a +1 to all values for net and site on non CapMax Tier 3, but the ETSI manual doesn't show to do that, I just did it to make it match DSDplus, otherwise, I'd get a lot of complaints about it or something.

**Comment by kantooon** [comment]
Attaching the broadcast PDUs recording (the relevant stuff is toward the end of it).
[bcast.bin.tar.gz](https://github.com/lwvmobile/dsd-fme/files/13770172/bcast.bin.tar.gz)

> Also, on your homebrew DMR site, is your net/site id set to 1-1.2, or is it supposed to be 0-0.1? Or something else. I had been adding a +1 to all values for net and site on non CapMax Tier 3, but the ETSI manual doesn't show to do that, I just did it to make it match DSDplus, otherwise, I'd get a lot of complaints about it or something.

I wouldn't worry about it. What you're doing is probably correct. The radios only display the system identity code, which is 9 in my case, but the CPS displays a net id of 0 as Net 1, and the same for the site id. To me only the whole 14 bit system identity code is relevant as that's what is displayed on the radio.

**Comment by lwvmobile** [comment]
Okay, this is what I am currently getting on those chan_freq PDUs with what I've written so far. Don't know if its correct or not, you'll have to let me know.

```
04:52:15 Sync: +DMR  [slot1]  slot2  | Color Code=01 | MBCC
 Announcements (C_BCAST) Announce Logical Channel/Frequency Relationship (Chan_Freq)
 LPCN: 0001; RX Base: 434000000; RX Step: 900000; RX Freq: 434900000;
             TX Base: 431000000; TX Step: 900000; TX Freq: 431900000;
  SYS: 0009; Reg: 1; Backoff: 2; BParms1: 0000; BParms2: 000001;
  MBC Op: 28; CC: 0; RES1: 0; RES2: 0; CDEFTYPE: 0; CDEFPARMS: 0005AFE10365C20;
 Slot 1 - Multi Block Control Message
  28002800120027000001A427
  A80000005AFE10365C206DF7
   
 DMR PDU Payload [A8][00][00][00][5A][FE][10][36][5C][20][6D][F7]
04:52:15 Sync: +DMR   slot1  [SLOT2] | Color Code=01 | VC4 
 AMBE 55489BFCE10480 err = [0] [0] 
 AMBE 546C8DA0E83100 err = [0] [0] 
 AMBE 55999790B08A00 err = [0] [0] 

 SLC_C_SYS_PARMS: Tiny; Net ID: 2; Site ID: 1.2; Reg Req: 1; CSC: 1; SYS: 0009;
 SLCO Completed Block [20][02][60][1F][B0]
04:52:15 Sync: +DMR  [slot1]  slot2  | Color Code=01 | MBCH
 DMR PDU Payload [28][00][28][00][12][00][27][00][00][02][94][44]
04:52:15 Sync: +DMR   slot1  [SLOT2] | Color Code=01 | VC5 
 AMBE 537A972A29EC00 err = [0] [0] 
 AMBE 507F9338EAD200 err = [0] [0] 
 AMBE 546C7BF39B8400 err = [0] [0] 
04:52:15 Sync: +DMR  [slot1]  slot2  | Color Code=01 | MBCC
 Announcements (C_BCAST) Announce Logical Channel/Frequency Relationship (Chan_Freq)
 LPCN: 0002; RX Base: 434000000; RX Step: 950000; RX Freq: 434950000;
             TX Base: 431000000; TX Step: 950000; TX Freq: 431950000;
  SYS: 0009; Reg: 1; Backoff: 2; BParms1: 0000; BParms2: 000002;
  MBC Op: 28; CC: 0; RES1: 0; RES2: 0; CDEFTYPE: 0; CDEFPARMS: 0009AFED8365DB0;
 Slot 1 - Multi Block Control Message
  280028001200270000029444
  A80000009AFED8365DB05528
   
 DMR PDU Payload [A8][00][00][00][9A][FE][D8][36][5D][B0][55][28]
04:52:15 Sync: +DMR   slot1  [SLOT2] | Color Code=01 | VC6 
 SLOT 2 TGT=1464200 SRC=5051695 FLCO=0x00 FID=0x00 SVC=0x00 Group Call  
 DMR PDU Payload [00][00][00][16][57][88][4D][15][2F]
 AMBE 53483FC22AEC00 err = [0] [0] 
 AMBE 534EB6A18B2700 err = [0] [0] 
 AMBE 534B3890AC2180 err = [0] [0] 
 SB: 00000000000 - 000; 

 SLC_C_SYS_PARMS: Tiny; Net ID: 2; Site ID: 1.2; Reg Req: 1; CSC: 1; SYS: 0009;
 SLCO Completed Block [20][02][60][1F][B0]
04:52:15 Sync: +DMR  [slot1]  slot2  | Color Code=01 | MBCH
 DMR PDU Payload [28][00][28][00][12][00][27][00][00][03][84][65]
04:52:15 Sync: +DMR   slot1  [SLOT2] | Color Code=01 | VC1 
 AMBE 533F323084CF80 err = [0] [0] 
 AMBE 504EB2D084E980 err = [0] [0] 
 AMBE 524C7396AC7300 err = [0] [0] 
04:52:15 Sync: +DMR  [slot1]  slot2  | Color Code=01 | MBCC
 Announcements (C_BCAST) Announce Logical Channel/Frequency Relationship (Chan_Freq)
 LPCN: 0003; RX Base: 434000000; RX Step: 850000; RX Freq: 434850000;
             TX Base: 431000000; TX Step: 850000; TX Freq: 431850000;
  SYS: 0009; Reg: 1; Backoff: 2; BParms1: 0000; BParms2: 000003;
  MBC Op: 28; CC: 0; RES1: 0; RES2: 0; CDEFTYPE: 0; CDEFPARMS: 000DAFD48365A90;
 Slot 1 - Multi Block Control Message
  280028001200270000038465
  A8000000DAFD48365A90AA80
   
 DMR PDU Payload [A8][00][00][00][DA][FD][48][36][5A][90][AA][80]
04:52:15 Sync: +DMR   slot1  [SLOT2] | Color Code=01 | VC2 
 AMBE 524F3A70846F80 err = [0] [0] 
 AMBE 527CD6BB63DC80 err = [0] [0] 
 AMBE 529807DBA20580 err = [0] [0] 

 SLC_C_SYS_PARMS: Tiny; Net ID: 2; Site ID: 1.2; Reg Req: 1; CSC: 1; SYS: 0009;
 SLCO Completed Block [20][02][60][1F][B0]
04:52:15 Sync: +DMR  [slot1]  slot2  | Color Code=01 | MBCH
 DMR PDU Payload [28][00][28][00][12][00][27][00][00][04][F4][82]
04:52:15 Sync: +DMR   slot1  [SLOT2] | Color Code=01 | VC3 
 AMBE 50883D7484B880 err = [0] [0] 
 AMBE 52763F308CBB80 err = [0] [0] 
 AMBE 508D01322CFC80 err = [0] [0] 
04:52:15 Sync: +DMR  [slot1]  slot2  | Color Code=01 | MBCC
 Announcements (C_BCAST) Announce Logical Channel/Frequency Relationship (Chan_Freq)
 LPCN: 0004; RX Base: 434000000; RX Step: 825000; RX Freq: 434825000;
             TX Base: 431000000; TX Step: 825000; TX Freq: 431825000;
  SYS: 0009; Reg: 1; Backoff: 2; BParms1: 0000; BParms2: 000004;
  MBC Op: 28; CC: 0; RES1: 0; RES2: 0; CDEFTYPE: 0; CDEFPARMS: 0011AFCE43659C8;
 Slot 1 - Multi Block Control Message
  28002800120027000004F482
  A80000011AFCE43659C82D6A
   
 DMR PDU Payload [A8][00][00][01][1A][FC][E4][36][59][C8][2D][6A]
```

> I wouldn't worry about it. What you're doing is probably correct. The radios only display the system identity code, which is 9 in my case, but the CPS displays a net id of 0 as Net 1, and the same for the site id. To me only the whole 14 bit system identity code is relevant as that's what is displayed on the radio.

Oh, okay, thanks for clarifying that. I also went ahead and added the syscode to the console output now along with the net/site value if that's of value to you.

Normal Console Output:
```
04:36:09 Sync: +DMR  [slot1]  slot2  | Color Code=01 | CSBK
 C_ALOHA_SYS_PARMS: Tiny; Net ID: 2; Site ID: 1.2; Cat: AB; SYS: 0009;
04:36:09 Sync: +DMR   slot1  [SLOT2] | Color Code=01 | VC2 
 SLC_C_SYS_PARMS: Tiny; Net ID: 2; Site ID: 1.2; Reg Req: 1; CSC: 1; SYS: 0009;
```

Payload Enabled has extra info:
```
04:33:38 Sync: +DMR  [slot1]  slot2  | Color Code=01 | CSBK
 C_ALOHA_SYS_PARMS: Tiny; Net ID: 2; Site ID: 1.2; Cat: AB; SYS: 0009;
 Ver: 2; Active Connection; SF: 0; NR: E; Reg Required; Backoff: 4; MS: 16776916; ALLMSI; 
 DMR PDU Payload [99][00][09][01][D4][00][27][FF][FE][D4][5E][BC]
```

Ncurses Terminal:
![Screenshot from 2023-12-26 04-54-19](https://github.com/lwvmobile/dsd-fme/assets/59371473/e8354b9e-3d10-49a3-be76-617248a817e0)

**Comment by kantooon** [comment]
Wow that was super quick, how can you move so fast? I want some of that coffee lol.

The channel/frequencies decoded are correct, so my code is right too. One thing I'm confused about in this line:
MBC Op: 28; CC: 0; RES1: 0; RES2: 0; CDEFTYPE: 0;
What does CC:0 stand for? The PDU description says nothing about colour code, but if there should be one there, I'm definitely broadcasting the wrong one.

**Comment by lwvmobile** [comment]
> Wow that was super quick, how can you move so fast? I want some of that coffee lol.

I started working on it a couple days ago when you first mentioned it.



> What does CC:0 stand for? The PDU description says nothing about colour code, but if there should be one there, I'm definitely broadcasting the wrong one.

I think that is indeed color code, but only when its on the ~Ann_WD_TSCC~ VoteNow PDU. I may need to remove that, it may be an error to get it where I'm getting it.

**Comment by kantooon** [comment]
Oh ok. I haven't implemented yet announce/withdraw TSCC or adjacent site broadcasts, so I will need to take a look at those PDUs. Colour code then seems right to have in the display. Anyways, thanks for your work, I shall move on now to other features, so feel free to close this at your convenience. 

As I progress with my stuff, I can provide more recordings if you want to cross-check your work so just ask for what you need. I'm purposely not reading any existing code base to avoid duplicating any possible issues.

**Comment by lwvmobile** [comment]
Okay, well I just pushed the code for the C_BCAST PDUs and some other things. Its available now if you want to give it a try. If you can, try starting up with out the channel map csv file, and see if DSD-FME can map those channels out now by itself. It seemed to work on that bin file you sent me, and I'll have to keep my eye out for real world systems running those Chan_Freq PDUs and see if it works without an imported channel map.



> As I progress with my stuff, I can provide more recordings if you want to cross-check your work so just ask for what you need. I'm purposely not reading any existing code base to avoid duplicating any possible issues.

Well, I don' t know how reliable every element I have is, its good enough for trunking and tuning and listening to calls, but there is always the likely-hood of some things being incorrect, but I just don't know better, and its something that's never been noticed by somebody else. So, if I'm wrong and your wrong, then we are both wrong together, and we can agree to be wrong together.

**Comment by kantooon** [comment]
I just gave it a try, it works great, once it receives the PDU it starts tuning to the right frequency. Hopefully this will be useful for systems in the wild as well (I'm broadcasting this PDU pretty frequently on my system, like every 2 minutes or so).

**Comment by lwvmobile** [comment]
Okay, sounds good. I suppose I'll go ahead and close this one as well. Just let me know if anything new there isn't quite working right or as expected if you notice anything.
