### ISSUE TITLE
command line key entry no longer works

### ISSUE THREAD

**Issue by HighVoltage73** [lwvmobile/dsd-fme#185]
I used to enter -K <key> on the command line for scrambler key entry and I cannot find it in the new documentation. I updated to the lastest from the old pulseaudio branch. Is there a command line switch for key entry anymore?

**Comment by lwvmobile** [comment]
Its `-b 69` now, for example. Big K and little k got repurposed to do key import files. See `dsd-fme -h` for more details, or see the updated (mostly updated) example usage and other documentation for more information on potential changes and new things.

**Comment by HighVoltage73** [comment]
Thanks. I looked through examples and didn’t see it.

**Comment by lwvmobile** [comment]
Oh, wait, you said 'Scrambler' Key, so do you mean for NXDN, or a BP key for DMR? 

If you want to enter an NXDN or dPMR scrambler key, use `-R 12345` instead.

**Comment by lwvmobile** [comment]
Any other questions, concerns, etc? If not, I'll close down this issue soon.
