### ISSUE TITLE
Can't select output audio device (Win), how to do it?

### ISSUE THREAD

**Issue by santus118** [lwvmobile/dsd-fme#192]
Hello, friends. How to select -o device? Don't work by nubers (1/2/3), by path (\ROOT\MEDIA\0001), by name in '' or ""
In -h hints not found :-(

**Comment by lwvmobile** [comment]
There isn't a way currently in DSD-FME to select output hardware audio devices, if not using audio devices and not, say, UDP or something. You can use the Windows Volume Mixer in Windows 10/11, and Pulse Audio Volume Control in Linux (pavucontrol), and select which output device you want it to use.

![Screenshot_85](https://github.com/lwvmobile/dsd-fme/assets/59371473/c167cc74-6e82-4be3-a52e-dee72e2600a4)


Are you trying to select audio hardware, or output files, like decoded wav files, etc? I noticed you had a path listing, but didn't know if you mistook seeing  something like '/dev/dsp' as a path and not hardware (which in Unix/Linux, some old hardware devices were, and still, are listed as a path/file  and not an abstraction or server 'pulse', 'jack', 'pipewire', etc).
