### ISSUE TITLE
P25 Phase 1 0xAA Debug data

### ISSUE THREAD

**Issue by secup** [lwvmobile/dsd-fme#196]
Hi there,

Does anyone have by any chance some IMBE codewords along with MI ?

I'm looking for first few voice frames ...

If ppl tested with a known key, that would be also great.

**Comment by lwvmobile** [comment]
I'm sorry, but this isn't the right place to request for your personal research into this matter. You'll have to inquire in other places, but trying to stay on the up and up here at any rate, so I'm afraid I'll have to shut this request down.
