### ISSUE TITLE
RC4 decryption not working with Anytone in ARC4 mode

### ISSUE THREAD

**Issue by craftbyte** [lwvmobile/dsd-fme#249]
I tried testing RC4 decryption with my anytone on FW ver 3.03 and was unable to decrypt it correctly after entering the same key I entered in the CPS. Is there a key format mismatch or did anytone change something?

**Comment by lwvmobile** [comment]
Nothing has changed as far as RC4 in DSD-FME for quite a while, so I don't suspect that is the issue. Just out of curiosity, which version of DSD-FME are you using, and what does the output of the terminal or log show when you attempt to decrypt / decode your radio? Any errors, or anything like that? Also, what command are you using to start up with?

**Comment by Yorch23** [comment]
Hello, tested with Anytone 578 latest version and the ARC4 system works without problem.

**Comment by lwvmobile** [comment]
So, still need assistance on this? If not, or no update with information I suggested, then I'm going to close as stale.

**Comment by craftbyte** [comment]
It appears the issue only happens on the Windows Cygwin version with no patched. After trying on a Pi today (since my Windows machine is not available) it works fine.
Sorry for taking up your time...
