### ISSUE TITLE
DMR: Change per-call file name depending on GC or PC

### ISSUE THREAD

**Issue by craftbyte** [lwvmobile/dsd-fme#258]
Currently, both DMR Private and Group Calls have TG in their filename. Could it be changed to RID or something similar if a PC is done instead of a GC?

**Comment by lwvmobile** [comment]
Perhaps eventually, but its extremely low priority right now. The whole back end for per call has to be re-written along with call history, and I'm not opening that can of worms anytime soon.

**Comment by lwvmobile** [comment]
Okay, so, this is what the call is going to look like now on DMR, I've changed the TG to a more vague DST, and also added a Private / Group string.

`./WAV/20240521 094659 CC 4 - Private - DST 647 - SRC 669.wav`

![Screenshot from 2024-05-21 09-49-12](https://github.com/lwvmobile/dsd-fme/assets/59371473/90e6694a-6497-44e9-b571-01822843b3a8)
