### ISSUE TITLE
dsd-fme core dumped

### ISSUE THREAD

**Issue by Mudary** [lwvmobile/dsd-fme#259]
Digital Speech Decoder: Florida Man Edition
 ██████╗  ██████╗██████╗     ███████╗███╗   ███╗███████╗
 ██╔══██╗██╔════╝██╔══██╗    ██╔════╝████╗ ████║██╔════╝
 ██║  ██║╚█████╗ ██║  ██║    █████╗  ██╔████╔██║█████╗  
 ██║  ██║ ╚═══██╗██║  ██║    ██╔══╝  ██║╚██╔╝██║██╔══╝  
 ██████╔╝██████╔╝██████╔╝    ██║     ██║ ╚═╝ ██║███████╗
 ╚═════╝ ╚═════╝ ╚═════╝     ╚═╝     ╚═╝     ╚═╝╚══════╝
Build Version: AW 2024-225-g79d5b79 
MBElib Version: 1.3.4
CODEC2 Support Enabled
Audio In/Out Device: pulse
Assertion 'p' failed at ../src/pulse/simple.c:313, function pa_simple_read(). Aborting.
Aborted (core dumped)

Ubuntu Jammy
Intel® Core™ i5-8350U CPU @ 1.70GHz × 8
Mesa Intel® UHD Graphics 620 (KBL GT2)
ssd 512G
x_64  X11

**Comment by lwvmobile** [comment]
If you got a `function pa_simple_read(). Aborting` error, it means it couldn't open or read from the pulse input device, so assuming for whatever reason, the pulse audio (or pipewire-pa plugin) server isn't running in the background, or you don't have any input audio hardware. If I recall correctly, its been a while, but in a few of our old remote sessions, I seem to recall you having some bluetooth hardware device or something, or some custom setup on the audio side that didn't always work.

What command are you running when you start up? Also, what is the output of the commands 

`pactl list short sources` 

```
1	alsa_output.pci-0000_0d_00.3.analog-stereo.monitor	module-alsa-card.c	s16le 2ch 44100Hz	RUNNING
2	alsa_input.pci-0000_0d_00.3.analog-stereo	module-alsa-card.c	s16le 2ch 48000Hz	RUNNING
3	virtual_sink.monitor	module-null-sink.c	s16le 2ch 44100Hz	RUNNING
4	virtual_sink2.monitor	module-null-sink.c	s16le 2ch 48000Hz	RUNNING
36	alsa_output.pci-0000_0b_00.1.hdmi-stereo-extra1.monitor	module-alsa-card.c	s16le 2ch 48000Hz	RUNNING

```
and 

`pactl list short sinks`

```
1	alsa_output.pci-0000_0d_00.3.analog-stereo	module-alsa-card.c	s16le 2ch 44100Hz	IDLE
2	virtual_sink	module-null-sink.c	s16le 2ch 44100Hz	IDLE
3	virtual_sink2	module-null-sink.c	s16le 2ch 48000Hz	IDLE
35	alsa_output.pci-0000_0b_00.1.hdmi-stereo-extra1	module-alsa-card.c	s16le 2ch 48000Hz	RUNNING

```

**Comment by Mudary** [comment]
91	virtual_sink.monitor	PipeWire	float32le 2ch 48000Hz	RUNNING
98	virtual_sink2.monitor	PipeWire	float32le 2ch 48000Hz	RUNNING
mudary3@mudary3:~/dsd-fme$ pactl list short sinks
91	virtual_sink	PipeWire	float32le 2ch 48000Hz	IDLE
98	virtual_sink2	PipeWire	float32le 2ch 48000Hz	IDLE

and the command for dsd-fme is just dsd-fme.

**Comment by Mudary** [comment]
Update, its working now, thanks

**Comment by lwvmobile** [comment]
I'm going to go ahead and closed this since you figured it out, and also, there is now an error parser for pulse audio so it'll report any errors when opening the instance instead of crashing with a cryptic message.
