### ISSUE TITLE
I could get a copy of any dPMR samples

### ISSUE THREAD

**Issue by 1zxLi** [lwvmobile/dsd-fme#260]
I could get a copy of any dPMR samples ？
thank ！

**Comment by lwvmobile** [comment]
Its not much, but here is a few samples I have, they are probably the best samples I have, albeit very short ones. Should be able to play them back with:

`dsd-fme -fm -i dPMR_clear.wav` and `dsd-fme -fm -i dPMR_12013.wav -R 12013` 

https://ufile.io/geoww6zd

**Comment by 1zxLi** [comment]
wow,Thank you again  !

**Comment by lwvmobile** [comment]
No problem. Going to close as completed now.
