### ISSUE TITLE
Cant use per call file recording

### ISSUE THREAD

**Issue by ole-luk0e** [lwvmobile/dsd-fme#261]
Trying to record in separated files:
`rtl_fm ... | dsd-fme -f1 -i -  -7 /tmp/ramdisk/raw -P  -N 2> log.ans`

 log.ans:

Build Version: AW 2024-225-g79d5b79 
MBElib Version: 1.3.0
CODEC2 Support Enabled
Decoding only P25 Phase 1 frames.
**/tmp/ramdisk/raw directory does not exist
Creating directory /tmp/ramdisk/raw to save wav files**
AUTO and NXDN Per Call Wav File Saving Enabled. (NCurses Terminal Only)
**Error - could not open wav output file .//tmp/ramdisk/raw/DSD-FME-X1.wav
Error - could not open wav output file .//tmp/ramdisk/raw/DSD-FME-X2.wav**
Enabling NCurses Terminal.

/tmp/ramdisk/raw directory created successfully but its empty

**Comment by lwvmobile** [comment]
Okay, I looked at it, looks like I had some hard coded `./` for paths, I guess I was under the assumption a user wouldn't specify a hard coded path that wasn't directly in the same path as dsd-fme being executed. For now, I've pushed a commit that should be good enough to get you going, but you'll need to checkout and run the aw_dev_fix_dir branch for the time being until I can go through and thoroughly test all the other things and make sure nothing is randomly broken now with file directories and file creation / writing.

So, what you'll want to do is just make a new folder, and cd into it and run:

```
git clone https://github.com/lwvmobile/dsd-fme.git
cd dsd-fme
git checkout aw_dev
mkdir build
cd build
cmake ..
make
sudo make install
```

When you run your startup again, when you use `-7`, just make sure to leave off the final `/` on the directory, that still gets added in the string, so essentially, the command you mentioned "should" work okay now, from my own testing anyways.

By the way, any reason you are writing to `/tmp/ramdisk/raw/` for? What Distro / Environment is that?

**Comment by ole-luk0e** [comment]
Ubuntu 22.04
I'm doing police scanner with archive option. It creates about 3000 files per day and 30% of them are less than 10Kb (useless).
So for the purpose of saving ssd I record them at RAMDISK, then delete bad files, then compress them to OGG and finaly save to ssd.

**Comment by lwvmobile** [comment]
Oh, okay, sounds like you know what your doing then. Sometimes, I get random start up commands that make no sense, and the user has no idea why they are doing it either. 

Anyways, just let me know if that update works for you, or if you have any other things come up that need to be addressed.

**Comment by ole-luk0e** [comment]
> So, what you'll want to do is just make a new folder, and cd into it and run:

Aand now it works properly!
thank you very much for answear and for your work too

**Comment by lwvmobile** [comment]
> Aand now it works properly!

That's good to hear, and don't mean to poke the bear on this, but had another request #258 to add the private / group / emergency / enc labels to calls, and changes the TG value to a more vague DST, so just giving you a heads up. Not sure if you have any scripts that parse file names, but this is what the per call string is going to look like on Phase 1 going forward in the main branch as soon as I get around to making sure nothing else is randomly broken.

`Per Call - P1/20240521 095333 P1 - NAC 23B - Group - DST 11029 - SRC 8035971.wav`


![Screenshot from 2024-05-21 09-55-49](https://github.com/lwvmobile/dsd-fme/assets/59371473/261cca8c-337f-49b1-93f7-1704ddcb39fe)

**Comment by ole-luk0e** [comment]
Actually I don't know what does all this stuff mean :-) Its non-trunked ap25 radio, so maybe it has no sense. The only thing that I use is date and time to sort files in archive.
Can I ask you a question? Your app is almost perfect. The only problem I see is slow scanning speed. I have 7 freqs and it takes 14 sec to make a loop... too long. At same time rtl_fm uses different mechanism, it locks active freq almost imminently. Why do you scan freqs one-by-one instead of use some squelch level and lock freq that is above the threshold?

**Comment by lwvmobile** [comment]
Yeah, I think the default scan speed is greater than or equal to 1 second, plus any overhead for synchronization. You can try to turn it to zero, with the `-t 0` option, but I'm honestly not sure if it'll be able to properly synchronize with a signal with that little time. Also, that would be a good idea, like you mention, to use the squelch, but it also has to work within the confines of the synchronization loop to see if sync is there in the time it takes to stop. 

In the future, I'll try out your suggestion and see if we can do it based on a purely RMS vs SQL mechanic and see if that'll do or not. To be honest, the scan feature is just something that I tacked on using the same mechanics as the trunking mechanics, so constant channel tuning wasn't thought of in the implementation, just cycling like its looking for a control channel and waiting 1 second in-between tunes.
