### ISSUE TITLE
terminal ncurses formatting issue

### ISSUE THREAD

**Issue by youmslinky** [lwvmobile/dsd-fme#263]
I'm probably doing something wrong, but `dsd-fme -fi -N` ncurses mode doesn't display correct for me.

Any suggestions? I've already tried in a virtual TTY, different terminal emulators, other shells.

To me it looks like CR and LF issues, like terminal expecting CRLF, but only getting LF.

I used the arch install script.

![image](https://github.com/lwvmobile/dsd-fme/assets/19676327/b37fe077-8cd2-4bb1-b88b-c4cbf43f52bf)

```
OS: Manjaro Linux x86_64
Kernel: 5.15.154-1-MANJARO
Packages: 1789 (pacman), 6 (flatpak)
Shell: zsh 5.9
Resolution: 2560x1440
DE: Plasma 5.27.11
WM: KWin
Theme: [Plasma], Breeze [GTK2/3]
Icons: [Plasma], breeze [GTK2/3]
Terminal: st
Terminal Font: JoyPixels
Memory: 12988MiB / 15917MiB
```

**Comment by lwvmobile** [comment]
`dsd-fme -fi -N 2> log.ans`

**Comment by youmslinky** [comment]
Ahhh, all that info is on stderr.

thanks for the help, it works perfect now!

![image](https://github.com/lwvmobile/dsd-fme/assets/19676327/362ffa71-309c-46e1-afb8-0fdc94a7bb58)
