### ISSUE TITLE
Question about dpmr

### ISSUE THREAD

**Issue by 1zxLi** [lwvmobile/dsd-fme#264]
First of all, thank you very much for sharing several DPMR samples with me last time. But now I have a new question for you. Which Portable Radio did you use to collect your clean dpmr samples?
（KENWOOD or Motorola or ?）

I am a student and I am currently doing some experiments on dpmr.

Thank you very much

**Comment by lwvmobile** [comment]
I didn't create the samples, they were just sent to me from another user, so I can't say for certain what the make or model of the radio was, but the original files indicate it was a Kenwood radio. Other than that, I have no idea.
