### ISSUE TITLE
Google Drive files in Wiki not available

### ISSUE THREAD

**Issue by kermit112** [lwvmobile/dsd-fme#267]
It seems, that the files stored on Google Drive aren't available anymore. Is it possible to refresh the links?

**Comment by lwvmobile** [comment]
If you are referring to the links on the wiki, I am afraid I do not have those files from the Google Drive. That information was added by another user two years ago and some of those downloads were linked to his Google account, so I can't really help there. You should still be able to manually do the WSL and Cygwin 64-bit version without the downloads, just will have to do them manually.
