### ISSUE TITLE
Fedora compiled (FC41) Display issue

### ISSUE THREAD

**Issue by ImperiousLeader** [lwvmobile/dsd-fme#271]
Hi All,

I apologize if this as already been answered - didn't spot it digging through...
When running in Fedora (compiled as per readme's) the header displays perfectly but the lines from call history down are not terminating correctly, resulting in a broken display.
![Screenshot From 2024-11-20 15-15-48](https://github.com/user-attachments/assets/0f1b9a2d-f79f-4a59-9b76-b8753de34e21)

I have attached the screen shot.... is this my stupid error. 
I am starting DSD FME with :
dsd-fme -f1 -i rtl:0:143.325M:0:0:12.5 -T -o 3 -G ~/DSD-FME/group.csv -N

And the CC decode otherwise seems to be working correctly.

Regards,
Anthony

**Comment by lwvmobile** [comment]
Try this:

```
dsd-fme -f1 -i rtl:0:143.325M:0:0:12.5 -T -o 3 -G ~/DSD-FME/group.csv -N 2> /dev/null
```

You'll probably want to change the `-o 3` to something else as well, or just leave it off entirely. Running with Fedora, you can probably just safely omit that entirely and it will route audio out of the default audio device. If you need to specify an exact device on pulse, use

`dsd-fme -O` (big O) to list all devices, and look for its index number, and select it with `dsd-fme -o pulse:3`, for example.

**Comment by ImperiousLeader** [comment]
Yes, that worked - thank you for overcoming my  silliness - didn't realise the dev null was a prequisite - thank you for your patience :)
