### ISSUE TITLE
Cygwin Build Info

### ISSUE THREAD

**Issue by lwvmobile** [lwvmobile/dsd-fme#73]
I recently deleted the Cygwin branch due to it being out of date with the main project on the pulse audio branch, and with the same amount of work, the pulse audio branch can be built and run in Cygwin anyways.

Prior to deletion, I pulled the cheat sheet screenshots for cygwin dependencies and the build instructions, I'll post them here for reference. Also, note, if you really want to use the old precompiled WIndows version, build 9044, it should still be available in the release section, along with the source code.

Again, this is informational only, and **I will not support users attempting to build in cygwin** due to the myriad of little issues that come up with dependencies, performance issues, and so on. I highly recommend using a Linux VM if you are a Windows user and wish to use DSD-FME.

https://github.com/lwvmobile/dsd-fme/releases

##CYGWIN Dependencies - Install using the Cygwin Installer##

![dep1](https://user-images.githubusercontent.com/59371473/184411278-d4564264-55aa-46a0-8cf3-629ddf8b8224.png)

![dep2](https://user-images.githubusercontent.com/59371473/184411309-d8777c3a-ce22-4ee3-b1b6-c9306e6cc839.png)

![dep3](https://user-images.githubusercontent.com/59371473/184411328-a8bc26c2-06ce-4c77-a223-1daaf0506e87.png)

![dep4](https://user-images.githubusercontent.com/59371473/184411334-9d8da47c-8aa6-4bd7-91e1-5c0751745110.png)

wget -O itpp-latest.tar.bz2 http://sourceforge.net/projects/itpp/files/latest/download?source=files
tar xjf itpp*
#if you can't cd into this folder, double check folder name first
cd itpp-4.3.1 
mkdir build
cd build
cmake ..
make 
make install
cd ..
cd ..

git clone https://github.com/lwvmobile/mbelib
cd mbelib
mkdir build
cd build
cmake ..
make
make install
cd ..
cd ..

git clone https://github.com/lwvmobile/dsd-fme
cd dsd-fme
git branch -a
git checkout remotes/origin/pulseaudio
git checkout -b pulseaudio
git branch -a #double check to see if you are on pulseaudio branch
mkdir build
cd build
cmake ..
make 

//After make has successfully completed, go into the mbelib/build folder and copy cygmbe-1.dll and paste it into the dsd-fme/build folder.

##rebuild in cygwin from pulse audio branch for subsequent updates##

##Open your clone folder##
git pull https://github.com/lwvmobile/dsd-fme pulseaudio
##cd into your build folder##
cd build
cmake ..
make 
##only run make install if you want this to be your main DSD install##
make install

**Comment by iz4tow** [comment]
I think you can close this issue.
Wiki updated https://github.com/lwvmobile/dsd-fme/wiki/Windows---CYGWIN-(Not-recommended)

**Comment by lwvmobile** [comment]
> I think you can close this issue.

I've got to say, I'm thoroughly impressed by your dedication and coming up with all these methods for Windows users to be able to use DSD-FME. I never could find any reliable documentation on auto installing packages in Cygwin, didn't know you could use the installer itself to automate it. I did have a question though, how do you route audio into DSD-FME (or anythign else) in older versions of Windows, like Windows 7. Is there a good audio mixer application that does that. I know VBCables can route the audio, but I don't think I've ever seen a mixer similar to pavucontrol or pulsemixer.

**Comment by iz4tow** [comment]
I use Virtual Audio Cable, but Pulseaudio and Jack are also bettter (and opensource).

**Comment by iz4tow** [comment]
> > I think you can close this issue.
> 
> I've got to say, I'm thoroughly impressed by your dedication and coming up with all these methods for Windows users to be able to use DSD-FME. I never could find any reliable documentation on auto installing packages in Cygwin, didn't know you could use the installer itself to automate it. I did have a question though, how do you route audio into DSD-FME (or anythign else) in older versions of Windows, like Windows 7. Is there a good audio mixer application that does that. I know VBCables can route the audio, but I don't think I've ever seen a mixer similar to pavucontrol or pulsemixer.

I updated the guide for Cygwin adding a Cygwin-32bit procedure.

**Comment by iScottybotty** [comment]
Thank you! Appreciated. 👍

> > > I think you can close this issue.
> 
> > 
> 
> > I've got to say, I'm thoroughly impressed by your dedication and coming up with all these methods for Windows users to be able to use DSD-FME. I never could find any reliable documentation on auto installing packages in Cygwin, didn't know you could use the installer itself to automate it. I did have a question though, how do you route audio into DSD-FME (or anythign else) in older versions of Windows, like Windows 7. Is there a good audio mixer application that does that. I know VBCables can route the audio, but I don't think I've ever seen a mixer similar to pavucontrol or pulsemixer.
> 
> 
> 
> I updated the guide for Cygwin adding a Cygwin-32bit procedure. 
> 
>

**Comment by lwvmobile** [comment]
I'm going to officially close this as an 'issue' now and mark it as obsoleted by the wiki entry as it has more precise and an automated method of installation implemented.
