### ISSUE TITLE
Gr-dsdfme

### ISSUE THREAD

**Issue by gaur-yogesh** [lwvmobile/dsd-fme#86]
Can you please add a gnuradio wrapper and make a project like gr-dsd for your version of dsd?

Thanks.

**Comment by lwvmobile** [comment]
Sounds like it would make an interesting project some day, but I honestly don't know much about making things for GNURadio, other than a miserable attempt to make an NFM demodulator for another project that didn't necessarily go so well. I've also made a lot of changes to DSD, so I have no idea if all of those would fit in and just work if I tried to use the same model that gr-dsd uses.

What I really need right now is some serious work on the demodulation, something more reliable and accurate than the code that came in with DSD. I really need a CQPSK demodulator for Phase 2 and LSM systems.

**Comment by lwvmobile** [comment]
Closing as stale.
