### ISSUE TITLE
LRRP issue

### ISSUE THREAD

**Issue by gaur-yogesh** [lwvmobile/dsd-fme#87]
Hey i saw your video on youtube and i was trying to get lat-long of the source. But as i was following the procedure as shown on video after running command on terminal "dsd-fme -N 2> test.log". I am getting following error

![a](https://user-images.githubusercontent.com/98145069/192130540-da907578-3a02-4fc6-8ca8-84cfb7720647.jpeg)

How can i define phase 2 missing parameters and what are these parameters?

Thanks.

**Comment by lwvmobile** [comment]
> How can i define phase 2 missing parameters and what are these parameters?

Well, if you need to specify Phase 2 Parameters, then you can open the menu and manually enter them from the menu. In this case though, I wonder if that is a false positive on the sync, or if it is actually Phase 2 audio. Usually, if you are on a P25 system (phase 1 or phase 2) the Phase 2 parameters will fill themselves in from the control channel, but its possible to listen to a Phase 2 RF channel without signalling so you would need to fill those in manually.

If you are using pulse audio for input, how is your audio routing set up, and what type of source are you using? You may need to use the virtualsink.sh to set up your virtual sinks and then open pulse audio volume control 'pavucontrol' and route your radio audio into the virtual sync in the playback tab, and have DSD-FME listening to the monitor of virtual_sink in the recording tab.

**Comment by lwvmobile** [comment]
Also, if you need help with audio routing, you will want to do something like this, make sure to run the virtualsink.sh script first, you'll need to run it once per start up since its not persistent.

![Screenshot_605](https://user-images.githubusercontent.com/59371473/192131663-eb423da5-0740-4dd0-b9f8-97852dc0535d.png)

![Screenshot_606](https://user-images.githubusercontent.com/59371473/192131670-c3958262-82ce-4145-8e21-b5853122468c.png)

You can also follow along with the 2> log.txt file by running

`tail -f log.txt`

or you can open the menu and dump the DMR LRRP data to a file of choice and follow it either by seeing the raw data in the dump file, or use software like LRRP.exe or QGIS and the map to follow along. Hope that helps.

**Comment by gaur-yogesh** [comment]
well my input is rtl-sdr and i am trying to transmit through a motorola. The voice is coming out fine. My concern is that LRRP file is not getting created.

Thanks.

**Comment by lwvmobile** [comment]
> well my input is rtl-sdr and i am trying to transmit through a motorola. The voice is coming out fine. My concern is that LRRP file is not getting created.
> 
> Thanks.

If voice is coming out, sounds like you are set up fine. So, is it DMR BS, or MS/Simplex source? MS/Simplex data is not very reliable right now, so if its happening there, then it may not work. I disabled MS data mode unless you enable the payload with the -Z or the ncurses menu entry for it.

If you are using DMR BS, and you are not seeing LRRP, then you might want to check your log file for 1/2 or 3/4 rate data payload dumps and see if any LRRP decoding is taking place. If there isn't, then it either isn't any available on the repeater, or its in a format that I'm currently not set up to decode. 

Any chance you could submit a capture.bin file, wav file recording of the signal, or a chunk of the log with payload enabled for analysis if you aren't seeing any LRRP data?

Also, to note, depending on which LRRP file type you select to dump in the menu, the file should either be in the folder you are running DSD-FME out of, or in your home directory. Custom files usually go in the same directory your terminal is operating in, and the lrrp.txt file always goes to home directory, i.e. ~/lrrp.txt so its in a consistent place for the QGIS map to be able to find by default.

**Comment by lwvmobile** [comment]
> "Decode DMR (STEREO BS/MS)" is not available for me. "

Its apart of the 'XDMA' decoder class now, and works the same way.

**Comment by gaur-yogesh** [comment]
Thanks for the support. 
I enabled the "toggle payload to console" and here is the output. Turns out there is no location data here

 SLOT 1 TGT=1  SRC=2 FID=0x00 SVC=0x00  Clear/Unencrypted Call  
Full Voice Burst Payload [00][00][00][00][00][01][00][00][02][01]
 AMBE C80324654B6780 err = [0] [0] 
 AMBE C805707A6B1880 err = [0] [0] 
 AMBE D8123B86813380 err = [0] [1] 
13:13:53 Sync: +DMR MS MODE |  Frame Sync   | DMRSTEREO | VC1 
 AMBE E81330CD050C80 err = [0] [0] 
 AMBE E809646EAF8900 err = [1] [4] 
 AMBE 6B9EA5C1116300 err = [2] [3] 
13:13:53 Sync: +DMR MS MODE | Color Code=01 | DMRSTEREO | VC2 
 AMBE E616A54CA2B880 err = [3] [4] 
 AMBE E500418B24A380 err = [0] [2] 
 AMBE 8A1C8F05F2A300 err = [1] [1] 
13:13:53 Sync: +DMR MS MODE | Color Code=01 | DMRSTEREO | VC3 
 AMBE D81C3BAC048380 err = [0] [2] 
 AMBE B80DC6573A7300 err = [2] [3] 
 AMBE F32C0CA828E480 err = [2] [5] 
13:13:53 Sync: +DMR MS MODE | Color Code=04 | DMRSTEREO | VC4 
 AMBE D81353CE020080 err = [0] [1] 
 AMBE 802F5D49862680 err = [2] [4] 
 AMBE F804AD21AE6980 err = [2] [4] 
13:13:53 Sync: +DMR MS MODE | Color Code=04 | DMRSTEREO | VC5 
 AMBE E41D2102308100 err = [2] [5] 
 AMBE A81940B00B1080 err = [0] [1] 
 AMBE EE86770AAFA480 err = [2] [5] 
13:13:53 Sync: +DMR MS MODE | Color Code=04 | DMRSTEREO | VC6 

Full Voice Burst Payload [00][00][00][00][00][00][20][08][02][00]
 AMBE AC88332E131700 err = [1] [4] 
 AMBE 0822DF96CD0A80 err = [3] [3] 
 AMBE 2C2D8F88FD0080 err = [3] [4] 
13:13:53 Sync: +DMR MS MODE |  Frame Sync   | DMRSTEREO | VC1 
 AMBE E8A02B183C7200 err = [1] [3] 
 AMBE EABFCFE1625980 err = [2] [4] 
 AMBE D801B5AF2BD400 err = [2] [4] 
13:13:53 Sync: +DMR MS MODE | Color Code=04 | DMRSTEREO | VC2 
 AMBE D800F867CBB000 err = [0] [0] 
 AMBE 780541A22C6D00 err = [0] [1] 
 AMBE 78112C8C44A100 err = [0] [0] 
13:13:53 Sync: +DMR MS MODE | Color Code=01 | DMRSTEREO | VC3 
 AMBE 780395633C2E00 err = [0] [0] 
 AMBE D803486D6DF400 err = [1] [1] 
 AMBE E80330CF092100 err = [0] [1] 
13:13:53 Sync: +DMR MS MODE | Color Code=01 | DMRSTEREO | VC4 
 AMBE E819C9A9C16380 err = [0] [2] 
 AMBE D809D6E2A8B780 err = [1] [2] 
 AMBE A800854D5D3700 err = [0] [1] 
13:13:53 Sync: +DMR MS MODE | Color Code=01 | DMRSTEREO | VC5 
 AMBE A81961D9256200 err = [0] [2] 
 AMBE B80560EE2FA800 err = [0] [1] 
 AMBE E80948A24E8400 err = [1] [2] 
13:13:53 Sync: +DMR MS MODE | Color Code=01 | DMRSTEREO | VC6 
 SLOT 1 TGT=1  SRC=2 FID=0x00 SVC=0x00  Clear/Unencrypted Call  
Full Voice Burst Payload [00][00][00][00][00][01][00][00][02][01]
 AMBE E8106161866480 err = [0] [0] 
 AMBE C80356EF6FAA00 err = [1] [1] 
 AMBE C802C02CCF2E80 err = [2] [2] 
13:13:53 Sync: +DMR MS MODE | Color Code=01 | (CRC OK ) | TLC           
 SLOT 1 TGT=1 SRC=2 FID=0x00 SVC=0x00 
Full TLC Payload [00][00][00][00][00][01][00][00][02][8D][6A][62]
13:13:53 Sync: +DMR MS MODE | Color Code=00 | (CRC OK ) | PI Header     
 Slot 1 DMR PI Header ALG ID: 0x00 KEY ID: 0x00 MI: 0x00020000 
Full PI Header Payload [00][00][00][00][02][00][00][00][00][00][00][00]
Sync: no sync
Press CTRL + C to close.

**Comment by lwvmobile** [comment]
Yeah, not seeing any in there either. For what its worth though, for the time being, all the samples I have with extra data in it that is Simplex sourced, the data decoding is pretty bad all the way around. Usually, in MS/Simplex, usually the first data burst after a no sync will always be bad, and the subsequent data might be okay, and any data immediately trailing a voice burst will usually be okay, like the TLC, but you may get a bogus decode like that trailing PI header, that's another bad decode. The way Simplex works by skipping a time slot (which is just noise) just throws fits for the current demodulator, it really wasn't written to handle that sort of on and off signalling quick signal switching.

Just also, I noticed you are running the dongle on a VFO bandwidth of 8, you might try bumping that up to 12 if your voice decodes aren't as good as they should be, see if that helps some. It might also clean up some of those spurious false P2 syncs. I may have to also have DMR Stereo return as a seperate decoder without the P25 stuff to help prevent those types of falsings as well.
