### ISSUE TITLE
Piping input

### ISSUE THREAD

**Issue by gaur-yogesh** [lwvmobile/dsd-fme#88]
Hello, as we can mention "-i rtl" and pipe-in stream from Rtl sdr. 
Is there a way i can pipe-in input from any other SDR ?

Thanks.

**Comment by lwvmobile** [comment]
Well, its probably more accurate to say that using `-i rtl ` in conjunction with certain switches actually activates an internal API to control an RTL dongle and take samples directly from it, rather that to stream it in. When you say stream it in, I interpret that as using external software to pipe audio in, either through the STDIN pipe, or the pulse audio input stream.

In the case of the latter, I normally just recommend using an application like GQRX or SDR++ with the software and just piping it into a virtual sink (see virtualsink.sh and pulse audio volume control). Those applications (and others) support a larger range of hardware, so its not limited to just RTL input.
