### ISSUE TITLE
dsd-fme main freezing

### ISSUE THREAD

**Issue by Mudary** [lwvmobile/dsd-fme#95]
Linux mudary1 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux.
Was running very well on pulseaudio, then installed the main branch and built that. Now my dsd-fme ncurses screen freezes. Any suggestions?

mudary1@mudary1:~/dsd-fme/build$ cmake ..
CMake Deprecation Warning at CMakeLists.txt:2 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Warning (dev) at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (PulseAudio)
  does not match the name of the calling package (PULSEAUDIO).  This can lead
  to problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/FindPULSEAUDIO.cmake:44 (find_package_handle_standard_args)
  CMakeLists.txt:17 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/mudary1/dsd-fme/build

**Comment by lwvmobile** [comment]
> Linux mudary1 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux.
> Was running very well on pulseaudio, then installed the main branch and built that. Now my dsd-fme ncurses screen freezes. Any suggestions?

Can you give me more information on your build environment and use case? What command are you using to start with?

**Comment by Mudary** [comment]
manual building, cut and paste with your manual build commands.
git clone https://github.com/lwvmobile/dsd-fme
cd dsd-fme
sudo cp tone8.wav /usr/share/
sudo cp tone24.wav /usr/share/
sudo cp tone48.wav /usr/share/
sudo chmod 777 /usr/share/tone8.wav
sudo chmod 777 /usr/share/tone24.wav
sudo chmod 777 /usr/share/tone48.wav
mkdir build
cd build
cmake ..
make -j `nproc`
sudo make install
sudo ldconfig

**Comment by Mudary** [comment]
What in doing now is removing dsd-fme and dsd pulseaudio. Than reinstalling pulseaudio, and reinstalling manually installing just the one main branch

**Comment by Mudary** [comment]
Have removed both dsd-fme/pulseaudio, and reinstalled pulseaudio and dsd-fme main branch, building with no problems, and no problems with operation. Ill leave this open until tomorrow. Great work by you and those who helped you. Thank you.

**Comment by Mudary** [comment]
Hi lwvmobile, I was using dsd-fme -N 2> log.log, It working fine, no problems when I uninstalled both branches as pulseaudio and main, and installed just the main branch. My problem was " trying to install on top of the same build folder as the old version." This can be closed now.

**Comment by lwvmobile** [comment]
Okay, just wanted to make sure, I was going to rename this threat so others can easily identify it if they have the same issue.
