### ISSUE TITLE
Support for TETRA calls

### ISSUE THREAD

**Issue by alphapats** [lwvmobile/dsd-fme#96]
Can you integrate TETRA calls interception in this project? Tetra live interception repository already exists in GitHub (link here (https://github.com/sq5bpf/telive).  ) https://www.rtl-sdr.com/tag/telive/ . It would make dsd-fme most versatile open source digital speech decoder software.

**Comment by lwvmobile** [comment]
I'll try to look into it sometime. I don't have tetra access where I live, and never really get any requests for it or samples of it (I think I may have received one or two small samples) so its not really something really high on my priority list for the time being. I'm almost afraid if I started working on it, it may wind up like my Yaesu implememtation (quit after one day)

**Comment by alphafox02** [comment]
If you start looking at Tetra, this also works and may be helpful. It's also newer. I grabbed some IQ files and played them back in the past to verify it's functions. 
https://gitlab.com/larryth/tetra-kit

**Comment by romanremus** [comment]
it would be great to add tetra, but unfortunately in my country, tetra is also encrypted.....

**Comment by Partfi10** [comment]
Hi, several radio networks in my country are unencrypted. I am able to upload some samples, if interested. Just say how long the samples should be and what they should contain.

**Comment by lwvmobile** [comment]
> Hi, several radio networks in my country are unencrypted. I am able to upload some samples, if interested. Just say how long the samples should be and what they should contain.

If you want to, doesn't need to be very long or anything like that, just needs voice and data in it. Also, no guarantees on this, I don't plan on doing much work on the project for a while, but maybe one day I'll get back around to adding things in.

**Comment by mrscanner2008** [comment]
I have TETRA network with my remote

**Comment by francisuk1989** [comment]
The only trouble with TETRA is the licensing somehow? There was a project for TETRA here https://github.com/moneriomaa/openear but it got pretty much shutdown as of DMCA, Event github shutdown the page for a little while.

**Comment by romanremus** [comment]
Lwvmobile, with tetra, I have a lot of min channels in the country, in fact only tetra is used for most emergency services, but unfortunately they are all encrypted

    Pe duminică, 30 iulie 2023 la 16:56:40 EEST, Francis ***@***.***> a scris:  
 
 


The only trouble with TETRA is the licensing somehow? There was a project for TETRA here https://github.com/moneriomaa/openear but it got pretty much shutdown as of DMCA, Event github shutdown the page for a little while.

**Comment by romanremus** [comment]
there is a tetra decoder plugin for sdrsharp, quite ok but the audio is encrypted, you have a link with the plugin {{{{{ https://forums.radioreference.com/threads/tetra-demodulator-trunk-tracking-demonstration.370639/ page-109 }}}}}, there you will find a download link and it is installed in sdrsharp, it uses 4 timeslot
    Pe duminică, 30 iulie 2023 la 17:31:45 EEST, ***@***.*** ***@***.***> a scris:  
 
  Lwvmobile, with tetra, I have a lot of min channels in the country, in fact only tetra is used for most emergency services, but unfortunately they are all encrypted

    Pe duminică, 30 iulie 2023 la 16:56:40 EEST, Francis ***@***.***> a scris:  
 
 


The only trouble with TETRA is the licensing somehow? There was a project for TETRA here https://github.com/moneriomaa/openear but it got pretty much shutdown as of DMCA, Event github shutdown the page for a little while.

**Comment by alphafox02** [comment]
If it helps, this works. I’ve used it before.

https://gitlab.com/larryth/tetra-kit

**Comment by romanremus** [comment]
does the decryption work too??? how can i use this software??
    Pe duminică, 30 iulie 2023 la 19:15:01 EEST, alphafox02 ***@***.***> a scris:  
 
 


If it helps, this works. I’ve used it before.

https://gitlab.com/larryth/tetra-kit

**Comment by alphafox02** [comment]
No it does not. I was only sharing with the idea it may help DSD-fme with unencrypted tetra decoding.

**Comment by iz4tow** [comment]
> The only trouble with TETRA is the licensing somehow? There was a project for TETRA here https://github.com/moneriomaa/openear but it got pretty much shutdown as of DMCA, Even github shutdown the page for a little while.

Here the new page https://github.com/chaoyi996/openear

**Comment by lwvmobile** [comment]
Just looking over the documents for TETRA a while back, and I discovered that TETRA uses a π/4-DQPSK or QAM modulation scheme, which, going by how well FME handles simulcast, I don't think this will work very well or at all if I coded it into DSD-FME as is. I would need to significantly re-write the demodulator to get this to work effectively, and I've decided that would work best as a new project from scratch (in the future) So, I won't be able to add TETRA, and even if I did, the demodulation would be so poor it wouldn't be very good at all.
