### ISSUE TITLE
PipeWire Support?

### ISSUE THREAD

**Issue by Fwappy** [lwvmobile/dsd-fme#99]
I am running Fedora 36, with the default backend of PipeWire. `cmake` fails with message `-- Could NOT find PulseAudio (missing: PULSEAUDIO_LIBRARY PULSEAUDIO_MAINLOOP_LIBRARY PULSEAUDIO_SIMPLE_LIBRARY PULSEAUDIO_INCLUDE_DIR)`

**Comment by lwvmobile** [comment]
Should work with Pipewire just fine, you just need to install the dev packages in order to build the software.

https://packages.fedoraproject.org/pkgs/pipewire/pipewire-devel/

Along with other dependencies if you haven't installed any yet. I don't have a list of exact ones for Fedora, but you'll probably want to use this as a base line and look for the equivalent packages as you go along.

https://github.com/lwvmobile/dsd-fme/blob/main/examples/Install_Notes.md#manual-install

**Comment by lwvmobile** [comment]
This one: https://packages.fedoraproject.org/pkgs/pulseaudio/pulseaudio-libs-devel/

I thnk I linked to the wrong library in the first one. Not entirely sure. If I have some free time, I'll try to install Fedora in a VM and experiment and figure out all the dependencies. Haven't tried Fedora in a few years.

**Comment by lwvmobile** [comment]
Okay, here is what I installed in a clean Fedora 37 (hopefully should all be the same for Fedora 36) inside of a VM to get it built and working.

Install Fedora Dependencies from Repo
```
sudo dnf install libsndfile-devel fftw-devel lapack-devel rtl-sdr-devel pulseaudio-libs-devel libusb-devel cmake git ncurses ncurses-devel gcc wget pavucontrol gcc-c++
```
Manually Install ITPP
```
wget -O itpp-latest.tar.bz2 http://sourceforge.net/projects/itpp/files/latest/download?source=files
tar xjf itpp*
#if you can't cd into this folder, double check folder name first
cd itpp-4.3.1
mkdir build
cd build
cmake ..
make -j `nproc`
sudo make install
sudo ldconfig
cd ..
cd ..
```

Clone/Build MBELIB
```
git clone https://github.com/lwvmobile/mbelib
cd mbelib
mkdir build
cd build
cmake ..
make -j `nproc`
sudo make install
sudo ldconfig
cd ..
cd ..
```

Clone and Install FME
```
git clone https://github.com/lwvmobile/dsd-fme
cd dsd-fme
sudo cp tone8.wav /usr/share/
sudo cp tone24.wav /usr/share/
sudo cp tone48.wav /usr/share/
sudo chmod 777 /usr/share/tone8.wav
sudo chmod 777 /usr/share/tone24.wav
sudo chmod 777 /usr/share/tone48.wav
mkdir build
cd build
cmake ..
make -j `nproc`
sudo make install
sudo ldconfig
```
Cmake may give a warning about PusleAudio calling name misamtch. Its just a warning, but will still find the pulse audio dev stuff.

if you get the message after installing when trying to run dsd-fme about libbme.so not found, then run this.

`sudo cp /usr/local/lib64/libmbe* /usr/local/lib`

and see if it can find it after that. I got hung up on that for a bit, so I think that's the correct solution. I ended up copying the entire contents of lib64 to lib, but I don't think that's the best solution, may cause issues on a loaded install vs a clean install. I have no idea.

**Comment by Fwappy** [comment]
Works! Thank you so much!
